Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2021-10, with the labels that each got.

#1679 [story/ECP-887] - Add GOVUK Notify SMS functionality
  CHANGELOG.md
  app/controllers/claims_controller.rb
  app/controllers/reminders_controller.rb
  app/models/claim.rb
  app/models/concerns/one_time_password_checkable.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/claims/email_address.html.erb
  config/application.rb
  db/migrate/20210923112453_add_mobile_verified_to_claim.rb
  db/schema.rb
  lib/notify_sms_message.rb
  lib/one_time_password/validator.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/early_career_payments_with_mobile_sms_otp_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/lib/notify_sms_message_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1690 [bug/ECP-1261] - Add GTM_Analytics to Azure
  CHANGELOG.md
  azure/terraform/modules/app_service/app_service.tf
  azure/terraform/modules/app_service/app_service_slot.tf
  azure/terraform/modules/app_service/data.tf
  azure/terraform/modules/container/container_group.tf
  azure/terraform/modules/container/data.tf
Labels: bug

#1694 [bug/ECP-1259] - Fix OTP not being enterable on changing contact details
  CHANGELOG.md
  app/controllers/claims_controller.rb
  app/models/claim.rb
  spec/factories/claims.rb
  spec/features/changing_answers_spec.rb
  spec/models/claim_spec.rb
Labels: bug, ruby

#1713 [story/ECP-1244] - Toggle Trainee Teacher text - future years
  CHANGELOG.md
  app/views/early_career_payments/claims/nqt_in_academic_year_after_itt.html.erb
Labels: enhancement, ruby
