Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2021-09, with the labels that each got.

#1608 [story/ECP-1161] - Add new question for Postgraduate Loans to ECP journey
  CHANGELOG.md
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/early_career_payments/slug_sequence.rb
  app/models/maths_and_physics/slug_sequence.rb
  app/models/student_loans/slug_sequence.rb
  app/views/claims/masters_doctoral_loan.html.erb
  config/locales/en.yml
  db/migrate/20210826080653_add_has_masters_doctoral_loan_to_claim.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/features/changing_answers_spec.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/claim/permitted_parameters_spec.rb
  spec/models/claim_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
  spec/models/maths_and_physics/slug_sequence_spec.rb
  spec/models/student_loans/slug_sequence_spec.rb
Labels: enhancement, ruby

#1609 [bug/ECP-1181] - Remove HTML 5 validation messages on National Insurance Number across all policies
  CHANGELOG.md
  app/views/claims/national_insurance_number.html.erb
  app/views/early_career_payments/claims/personal_details.html.erb
Labels: bug

#1619 [story/ECP-1079] - Add Plan Types 3 and 4 to payroll csv generator
  CHANGELOG.md
  app/models/payroll/payment_csv_row.rb
  spec/models/payroll/payment_csv_row_spec.rb
Labels: enhancement, ruby

#1623 [bug/ECP-1200] - Incorrect content in application submitted screen
  app/views/submissions/_confirmation.html.erb
Labels: bug

#1624 [bug/ECP-1201] - Update schools fixture data that is used in seeding
  spec/fixtures/schools.yml
Labels: bug, ruby

#1628 [story/ECP-81] - Add generic privacy statement replacing the existing individual policy privacy statements
  CHANGELOG.md
  app/views/static_pages/privacy_notice.html.erb
Labels: enhancement, ruby

#1629 [bug/ECP-1202] - Update link_to with correct path
  CHANGELOG.md
  app/controllers/reminders_controller.rb
  app/views/early_career_payments/claims/_ineligibility_reason_ineligible_nqt_in_academic_year_after_itt.html.erb
  spec/features/reminders_spec.rb
Labels: bug, ruby

#1630 [bug/ECP-1203] - Replace 'button_to, method: :get' to use 'link_to' to remove params ? at end of URL's
  CHANGELOG.md
  app/views/claims/information_provided.html.erb
  app/views/early_career_payments/claims/eligibility_confirmed.html.erb
  app/views/early_career_payments/claims/eligible_later.html.erb
  app/views/early_career_payments/claims/how_we_will_use_information_provided.html.erb
  app/views/maths_and_physics/claims/eligibility_confirmed.html.erb
  app/views/student_loans/claims/eligibility_confirmed.html.erb
  app/views/submissions/_completion.html.erb
Labels: bug, ruby

#1631 release-094
  CHANGELOG.md
Labels: ruby

#1634 [task/ECP-1218] - Fix deprecation warning: Passing the keyword argument as the last hash parameter is deprecated
  app/views/admin/claims/_tabs.html.erb
Labels: ruby

#1649 [story/ECP-995-997-998] - Add new trainee teacher journey
  CHANGELOG.md
  app/helpers/early_career_payments_helper.rb
  app/models/early_career_payments.rb
  app/models/early_career_payments/eligibility.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/eligible_itt_subject.html.erb
  app/views/early_career_payments/claims/future_eligibility.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
  spec/features/early_career_payments_trainee_teacher_spec.rb
  spec/features/ineligible_early_career_payments_claims_spec.rb
  spec/features/reminders_spec.rb
  spec/helpers/early_career_payments_helper_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1653 [task/ECP-1230] - Remove references to Azure ARM templates in README
  README.md
Labels: documentation

#1648 [story/ECP-443] - Combine Teacher Personal Details Onto One Page In The TSLR & M&P User Journeys
  CHANGELOG.md
  app/controllers/claims_controller.rb
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/maths_and_physics/slug_sequence.rb
  app/models/student_loans/slug_sequence.rb
  app/views/claims/date_of_birth.html.erb
  app/views/claims/name.html.erb
  app/views/claims/national_insurance_number.html.erb
  app/views/claims/personal_details.html.erb
  config/locales/en.yml
  spec/features/changing_answers_spec.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/claim_spec.rb
Labels: ruby

#1658 [task/ECP-1040] - Update specs to remove use of ActiveSupport::Duration
  spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
Labels: ruby

#1660 [task/ECP-1040] - first pass on upgrade
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1671 [task/ECP-1040] - Upgrade ruby from 2.7.0 to 2.7.1
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1672 [task/ECP-1040] - Bump ruby from 2.7.1 to 2.7.2
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1673 [task/ECP-1040] - Bump ruby from 2.7.2 to 2.7.3
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1674 [task/ECP-1040] - Bump ruby from 2.7.3 to 2.7.4
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1675 Revert "[task/ECP-1040] - Bump ruby from 2.7.3 to 2.7.4"
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby

#1677 [bug/ECP-1192] - Start page - 'check your eligibility today' link directs to wrong page
  CHANGELOG.md
  app/views/static_pages/landing_page.html.erb
Labels: bug
