Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2021-07, with the labels that each got.

#1464 [task/ECP-628] - upgrade rails from 6.0.3.6 to 6.0.3.7
  Gemfile
  Gemfile.lock
Labels: security

#1471 [story/ECP-872] - Update content for 'What is your address?' screen
  CHANGELOG.md
  app/views/claims/address.html.erb
  spec/features/early_career_payments_claim_spec.rb
Labels: enhancement, ruby

#1431 [story/ECP-488] - User Journey Page 22 - 'Eligible Later: We have set your reminders'
  app/controllers/reminders_controller.rb
  app/views/reminders/eligible_later_completion.html.erb
  app/views/reminders/personal_details.html.erb
  config/routes.rb
  spec/features/reminders_spec.rb
Labels: enhancement, ruby

#1429 [story/ECP-885] - Add 'Mobile number' screen
  CHANGELOG.md
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/claims/mobile_number.html.erb
  config/locales/en.yml
  db/migrate/20210625143438_add_mobile_number_to_claims.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/claim/permitted_parameters_spec.rb
  spec/models/claim_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1478 [story/ECP-857] - Update performance questions 'poor performance' and 'disciplinary action' combining them on a single screen
  CHANGELOG.md
  app/helpers/early_career_payments_helper.rb
  app/models/early_career_payments/eligibility.rb
  app/models/early_career_payments/eligibility_answers_presenter.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/_ineligibility_reason_poor_performance.html.erb
  app/views/early_career_payments/claims/poor_performance.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/features/ineligible_early_career_payments_claims_spec.rb
  spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1481 [bug/ECP-896] - remove hard coded value
  azure/terraform/modules/app_service/data.tf
  azure/terraform/modules/container/data.tf
  spec/lib/dqt/client_spec.rb
Labels: ruby, security

#1482 [story/ECP-886] - Add 'OTP verification for mobile number' screen
  app/controllers/claims_controller.rb
  app/models/claim.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/claim_mailer/email_verification.text.erb
  app/views/claims/_one_time_password.html.erb
  app/views/claims/_one_time_password_mobile.html.erb
  app/views/claims/email_verification.html.erb
  app/views/claims/mobile_verification.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/mailers/claim_mailer_spec.rb
  spec/models/claim_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1484 [task/ECP-1073] - Upgrade ruby from 2.6.7 to 2.6.8 to address CVE's
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby, security

#1489 Revert "[task/ECP-1073] - Upgrade ruby from 2.6.7 to 2.6.8 to address CVE's"
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: ruby, security

#1501 [story/ECP-459] - Add Ordnance Survey API client for Postcode and Address searches
  .env.test
  CHANGELOG.md
  config/application.rb
  config/initializers/ordnance_survey.rb
  lib/ordnance_survey.rb
  lib/ordnance_survey/api.rb
  lib/ordnance_survey/api/v1.rb
  lib/ordnance_survey/api/v1/search_places.rb
  lib/ordnance_survey/client.rb
  lib/ordnance_survey/client/response.rb
  lib/ordnance_survey/client/response_error.rb
  lib/ordnance_survey/configuration.rb
  spec/initializers/ordnance_survey_spec.rb
  spec/lib/ordnance_survey/api/v1/search_places_spec.rb
  spec/lib/ordnance_survey/api/v1_spec.rb
  spec/lib/ordnance_survey/api_spec.rb
  spec/lib/ordnance_survey/client/response_spec.rb
  spec/lib/ordnance_survey/client_spec.rb
  spec/lib/ordnance_survey/configuration/client_spec.rb
  spec/lib/ordnance_survey/configuration_spec.rb
  spec/lib/ordnance_survey_spec.rb
  spec/rails_helper.rb
  spec/support/ordnance_survey_helpers.rb
Labels: enhancement, ruby
