Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2021-05, with the labels that each got.

#1318 [story/ECP-503] - User Journey Page 35 - 'Did you take out a Postgraduate Master's Loan on or after 1 August 2016?'
  CHANGELOG.md
  app/models/early_career_payments/eligibility.rb
  app/models/early_career_payments/eligibility_answers_presenter.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/masters_loan.html.erb
  config/locales/en.yml
  db/migrate/20210430184810_add_postgraduate_masters_loan_to_early_career_payments_eligibilities.rb
  db/schema.rb
  spec/factories/early_career_payments/eligibilities.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
Labels: enhancement, ruby

#1314 [story/ECP-490] - User Journey Page 24 - 'Personal Details'
  app/models/claim.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/personal_details.html.erb
  config/locales/en.yml
  db/schema.rb
  spec/features/early_career_payments_claim_spec.rb
Labels: enhancement, ruby

#1315 [story/ECP-489] - User Journey Page 23 - 'How we will use the information you provide'
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/how_we_will_use_information_provided.html.erb
  spec/features/early_career_payments_claim_spec.rb
Labels: enhancement, ruby

#1327 [story/ECP-478] - Add 'Check your answers for eligibility?'
  CHANGELOG.md
  app/helpers/claims_helper.rb
  app/models/early_career_payments/eligibility_answers_presenter.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/early_career_payments/claims/check_your_answers_part_one.html.erb
  config/locales/en.yml
  spec/factories/claims.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
Labels: enhancement, ruby

#1328 [story/ECP-492] - Add Personal Details page 'Email Address' to ECP journey
  CHANGELOG.md
  app/helpers/claims/email_address_helper.rb
  app/models/claim.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/claims/email_address.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/helpers/claims/email_address_helper_spec.rb
Labels: enhancement, ruby

#1331 [story/ECP-506] - User Journey Page 38 - 'Application Complete'
  CHANGELOG.md
  app/controllers/submissions_controller.rb
  app/helpers/claims/show_helper.rb
  app/views/early_career_payments/claims/personal_details.html.erb
  app/views/submissions/_completion.html.erb
  app/views/submissions/_confirmation.html.erb
  app/views/submissions/show.html.erb
  config/routes.rb
  spec/features/early_career_payments_claim_spec.rb
Labels: enhancement, ruby

#1333 [story/ECP-581] - Add 'You are not eligible' (Subject) page
  CHANGELOG.md
  app/models/early_career_payments/eligibility.rb
  app/views/early_career_payments/claims/_ineligibility_reason_generic_ineligibility.html.erb
  app/views/early_career_payments/claims/_ineligibility_reason_itt_subject_none_of_the_above.html.erb
  app/views/early_career_payments/claims/_ineligibility_reason_not_teaching_now_in_eligible_itt_subject.html.erb
  app/views/early_career_payments/claims/_ineligibility_reason_subject_to_formal_performance_action.html.erb
  app/views/early_career_payments/claims/ineligible.html.erb
  config/locales/en.yml
  spec/features/ineligible_early_career_payments_claims_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
Labels: enhancement, ruby

#1335 [story/ECP-505] - Add 'Check your answers before sending your application' page to ECP journey
  CHANGELOG.md
  app/helpers/claims/check_your_answers_helper.rb
  app/helpers/claims/show_helper.rb
  app/views/claims/address.html.erb
  app/views/claims/bank_details.html.erb
  app/views/claims/check_your_answers.html.erb
  app/views/claims/gender.html.erb
  app/views/early_career_payments/claims/check_your_answers_part_one.html.erb
  app/views/early_career_payments/claims/disciplinary_action.html.erb
  app/views/early_career_payments/claims/eligible_itt_subject.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/helpers/claims/check_your_answers_helper_spec.rb
  spec/helpers/claims/show_helper_spec.rb
Labels: enhancement, ruby

#1339 [story/ECP-497] - User Journey Page 31 - 'Student Loans: When you applied for your student loan where was your home address?''
  CHANGELOG.md
  app/models/early_career_payments/slug_sequence.rb
  spec/features/early_career_payments_claim_spec.rb
Labels: enhancement, ruby

#1344 Revert "[task/ECP-319] - remove references to GOVUK Verify from Azure scripts"
  azure/resource_groups/alerts/template.json
  azure/resource_groups/app/parameters/development.template.json
  azure/resource_groups/app/parameters/production.template.json
  azure/resource_groups/app/parameters/test.template.json
  azure/resource_groups/app/template.json
  azure/templates/vsp.json
Labels: bug

#1356 [bug/ECP-643] - fix broken logic flows for 'Student Loans' sections of ECP journey
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/early_career_payments/eligibility.rb
  app/models/early_career_payments/slug_sequence.rb
  spec/factories/claims.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: bug, ruby

#1390 [story/ECP-873] - change duration of OTP from 60 to 900 seconds
  app/helpers/early_career_payments_helper.rb
  app/mailers/claim_mailer.rb
  app/views/claim_mailer/ecp_email_verification.text.erb
  app/views/early_career_payments/claims/_one_time_password.html.erb
  lib/one_time_password.rb
  spec/helpers/early_career_payments_helper_spec.rb
Labels: enhancement, ruby

#1398 [bug/ECP-903] - fix issue when 'No' is selected for Student Loans question and claim could failing valid?(:submit)
  app/models/early_career_payments/eligibility.rb
  spec/models/early_career_payments/eligibility_spec.rb
Labels: bug, ruby
