Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2021-08, with the labels that each got.

#1514 [bug/ECP-1120] - fix issues
  lib/ordnance_survey/api/v1/search_places.rb
  spec/lib/ordnance_survey/api/v1/search_places_spec.rb
  spec/support/ordnance_survey_helpers.rb
Labels: bug, ruby

#1517 [story/ECP-576] - Add home address search screen to claim journey
  CHANGELOG.md
  app/controllers/claims_controller.rb
  app/models/early_career_payments/slug_sequence.rb
  app/views/claims/address.html.erb
  app/views/claims/postcode_search.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
Labels: enhancement, ruby

#1520 [bug/ECP-1126] - Fix city/town assignment - move to address_line_3
  lib/ordnance_survey/api/v1/search_places.rb
  spec/lib/ordnance_survey/api/v1/search_places_spec.rb
Labels: bug, ruby

#1526 [story/ECP-836] - Add home address manual screen to ECP journey
  CHANGELOG.md
  app/helpers/claims_helper.rb
  app/views/claims/address.html.erb
  app/views/claims/postcode_search.html.erb
  app/views/claims/select_home_address.html.erb
  config/locales/en.yml
  spec/features/auto_populating_home_address_from_postcode_search.rb
  spec/features/changing_answers_spec.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
Labels: enhancement, ruby

#1527 [bug/ECP-1129] - Add missing change link
  app/views/claims/select_home_address.html.erb
  spec/features/auto_populating_home_address_from_postcode_search.rb
Labels: bug, ruby

#1528 [story/ECP-1130] - Move postgraduate masters and doctoral loan questions from ecp eligibilities to claims model
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/early_career_payments/eligibility.rb
  app/views/claims/doctoral_loan.html.erb
  app/views/claims/masters_loan.html.erb
  app/views/early_career_payments/claims/doctoral_loan.html.erb
  app/views/early_career_payments/claims/masters_loan.html.erb
  config/locales/en.yml
  db/migrate/20210807143601_add_postgraduate_masters_loan_to_claims.rb
  db/migrate/20210808190142_add_postgraduate_doctoral_loan_to_claims.rb
  db/migrate/20210809072246_remove_postgraduate_loans_from_early_career_payments_eligibilities.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/factories/early_career_payments/eligibilities.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/eligible_later_early_career_payments_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/claim/permitted_parameters_spec.rb
  spec/models/claim_spec.rb
  spec/models/early_career_payments/eligibility_spec.rb
Labels: ruby

#1530 [story/ECP-446] - Add postgraduate loan questions to MP and TSLR user journeys
  CHANGELOG.md
  app/helpers/claims_helper.rb
  app/models/claim.rb
  app/models/maths_and_physics/slug_sequence.rb
  app/models/student_loans/slug_sequence.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/helpers/claims_helper_spec.rb
  spec/models/claim_spec.rb
  spec/models/maths_and_physics/slug_sequence_spec.rb
  spec/models/student_loans/slug_sequence_spec.rb
Labels: enhancement, ruby

#1536 [story/ECP-1109] - DAC Report Issue 3, Error links missing
  app/views/claims/bank_or_building_society.html.erb
  app/views/claims/provide_mobile_number.html.erb
  app/views/early_career_payments/claims/eligible_itt_subject.html.erb
  app/views/early_career_payments/claims/itt_year.html.erb
Labels: bug, ruby

#1535 [story/ECP-460] - Add postcode lookup and selection to M+P and TSLR journeys
  CHANGELOG.md
  app/models/maths_and_physics/slug_sequence.rb
  app/models/page_sequence.rb
  app/models/student_loans/slug_sequence.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/models/maths_and_physics/slug_sequence_spec.rb
  spec/models/page_sequence_spec.rb
  spec/models/student_loans/slug_sequence_spec.rb
Labels: enhancement, ruby

#1538 [story/ECP-1113] - DAC Report Issue 7, Unlabelled Form
  CHANGELOG.md
  app/views/claims/_one_time_password.html.erb
  app/views/reminders/_one_time_password.html.erb
Labels: bug, ruby

#1541 [story/ECP-1108] - DAC Report Issue 2, Multiple Level 1 Headings
  CHANGELOG.md
  app/views/early_career_payments/claims/personal_details.html.erb
  app/views/early_career_payments/claims/poor_performance.html.erb
Labels: bug, ruby

#1539 [bug/ECP-1128] - Fix for address screens
  app/models/early_career_payments/slug_sequence.rb
  app/models/maths_and_physics/slug_sequence.rb
  app/models/page_sequence.rb
  app/models/student_loans/slug_sequence.rb
  spec/models/early_career_payments/slug_sequence_spec.rb
  spec/models/maths_and_physics/slug_sequence_spec.rb
  spec/models/page_sequence_spec.rb
  spec/models/student_loans/slug_sequence_spec.rb
Labels: bug, ruby

#1540 [story/ECP-1135] - DAC Report Issue 3, Error links missing for Bank or Building Society account page
  CHANGELOG.md
  app/models/claim.rb
  app/views/claims/personal_bank_account.html.erb
  spec/models/claim_spec.rb
Labels: bug, ruby

#1543 [story/ECP-1114] - DAC Report Issue 8, Non-Descriptive Links
  CHANGELOG.md
  app/views/claims/_one_time_password.html.erb
  app/views/static_pages/landing_page.html.erb
  config/locales/en.yml
  spec/features/early_career_payments_claim_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/features/validating_user_contact_details_spec.rb
Labels: bug, ruby

#1569 [bug/ECP-712] - Fix personal details error messages
  CHANGELOG.md
  app/controllers/claims_controller.rb
  app/models/claim.rb
  app/views/early_career_payments/claims/personal_details.html.erb
  spec/models/claim_spec.rb
Labels: bug, ruby

#1573 [bug/ECP-1143] - Remove rogue ? at end of heading
  config/locales/en.yml
Labels: bug, ruby

#1589 [bug/ECP-1158] - One off Data Migration to fix qualifications link throwing error
  db/data/20210827115900_update_ecp_claims_with_academic_year_2020_to_2021.rb
Labels: bug, ruby

#1601 [story/ECP-999] - Content Change to 'Performance issues' screen
  CHANGELOG.md
  config/locales/en.yml
Labels: enhancement, ruby

#1603 [story/ECP-1037] - Content change to 'Application complete' page to ensure teachers submit claim
  CHANGELOG.md
  app/views/submissions/_completion.html.erb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/ecp_eligible_now_reminder_set_spec.rb
Labels: enhancement, ruby

#1604 [story/ECP-1177] - Incorrect subject heading on TSLR and ECP OTP email
  CHANGELOG.md
  app/mailers/claim_mailer.rb
  config/locales/en.yml
Labels: enhancement, ruby
