Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2022-02, with the labels that each got.

#1834 [story/ECP-1379] - DqT Test data via CSV loader
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  db/seeds.rb
  db/seeds/base_importer.rb
  db/seeds/claims_seeder.rb
  db/seeds/data_importer.rb
  db/seeds/eligibilities/early_career_payments_seeder.rb
  lib/tasks/test_data_seeder.rake
  spec/fixtures/files/dqt_testing/ecp_test_seed_data_254_records.csv
  spec/fixtures/files/dqt_testing/ecp_test_seed_data_82_records.csv
  spec/fixtures/files/dqt_testing/ecp_test_seed_data_two_records.csv
Labels: enhancement, ruby

#1838 [bug/ECP-1385] - Fix broken seeding process and remove rake db:reset and associated tasks
  db/test_seeders/base_importer.rb
  db/test_seeders/claims_importer.rb
  db/test_seeders/data_importer.rb
  db/test_seeders/eligibilities/early_career_payments_importer.rb
  lib/tasks/test_data_seeder.rake
Labels: bug

#1840 [bug/ECP-1379] - move location of ar-copy gem, explicitly require when needed
  Gemfile
  db/test_seeders/base_importer.rb
Labels: bug

#1841 [bug/ECP-1379] - UUID changes so cannot be static for School.id
  db/test_seeders/eligibilities/early_career_payments_importer.rb
Labels: bug

#1845 [bug/ECP-1388] - fix load order for claims associated eligibilities to match csv dqt data
  db/test_seeders/base_csv_import_validator.rb
  db/test_seeders/base_importer.rb
  db/test_seeders/claims_importer.rb
  db/test_seeders/data/dqt_testing/ecp_test_seed_data_five_records.csv
  db/test_seeders/data_importer.rb
  db/test_seeders/eligibilities/early_career_payments.rb
  db/test_seeders/eligibilities/early_career_payments/csv_import_validator.rb
  db/test_seeders/eligibilities/early_career_payments/importer.rb
  db/test_seeders/eligibilities/early_career_payments_importer.rb
Labels: bug, ruby

#1846 [bug/ECP-1389] - Update DqT CSV ECP data - correct two entries - Mathematical Physics - Years
  db/test_seeders/claims_importer.rb
  db/test_seeders/data/dqt_testing/ecp_test_seed_data_254_records.csv
Labels: bug

#1848 [story/ECP-1380] - Add ability to bulk load test data for Payroll Testing
  db/test_seeders/base_csv_import_validator.rb
  db/test_seeders/base_importer.rb
  db/test_seeders/data_importer.rb
  db/test_seeders/decisions_importer.rb
  db/test_seeders/eligibilities/early_career_payments/importer.rb
  db/test_seeders/record_builder.rb
  db/test_seeders/seeder.rb
  lib/tasks/test_data_seeder.rake
Labels: enhancement, ruby

#1849 [story/ECP-1381] - Create test scripts for DqT Claim service - TSLR CSV
  CHANGELOG.md
  db/test_seeders/base_csv_import_validator.rb
  db/test_seeders/base_importer.rb
  db/test_seeders/claims_importer.rb
  db/test_seeders/data/dqt_testing/tslr_test_seed_data_24_records.csv
  db/test_seeders/data/dqt_testing/tslr_test_seed_data_98_records.csv
  db/test_seeders/data/dqt_testing/tslr_test_seed_data_two_records.csv
  db/test_seeders/data_importer.rb
  db/test_seeders/eligibilities/student_loans.rb
  db/test_seeders/eligibilities/student_loans/csv_import_validator.rb
  db/test_seeders/eligibilities/student_loans/importer.rb
  db/test_seeders/seeder.rb
  lib/tasks/test_data_seeder.rake
Labels: enhancement, ruby

#1850 [bug/ECP-1381] - Fix dqt_data:ecp|tslr rake task not loading due to wrong ENVIRONMENT_NAME details
  db/test_seeders/base_importer.rb
Labels: bug, ruby

#1861 [story/ECP-1393] - Add defensive exits to prevent accidently running DqT CSV data/Payroll UAT test data loaders running in PROD
  db/test_seeders/base_importer.rb
Labels: enhancement, ruby

#1865 [story/ECP-630] - De/allocating claims to claims checkers
  CHANGELOG.md
  app/controllers/admin/allocations_controller.rb
  app/helpers/admin/claims_helper.rb
  app/models/claim.rb
  app/models/dfe_sign_in/user.rb
  app/views/admin/claims/_allocations_form.html.erb
  app/views/admin/claims/index.html.erb
  app/views/admin/tasks/_claim_summary.html.erb
  app/views/admin/tasks/_task_outcome.html.erb
  app/views/shared/_assignment_banner.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220212232000_add_assigned_user_id_to_claims.rb
  db/schema.rb
  lib/claim_allocator.rb
  lib/claim_deallocator.rb
  spec/features/admin_claim_allocation_spec.rb
  spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/lib/claim_allocator_spec.rb
  spec/lib/claim_deallocator_spec.rb
  spec/models/claim_spec.rb
  spec/models/dfe_sign_in/user_spec.rb
Labels: enhancement, ruby

#1868 [bug/ECP-1390] - Decisions stats dashboard page showing incorrect data
  .gitignore
  CHANGELOG.md
  app/models/claim_decision.rb
  lib/send_analytics/decisions.rb
  lib/tasks/backfill_daily_stats_analytics.rake
  spec/lib/send_analytics/daily_stats_spec.rb
  spec/lib/send_analytics/decisions_spec.rb
Labels: bug
