Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2022-01, with the labels that each got.

#1743 [story/ECP-1288] - Add ITT Subject and ITT Subject Codes to task notes for DqT automation
  CHANGELOG.md
  app/models/automated_checks/claim_verifiers/qualifications.rb
  app/models/automated_checks/dqt_report_csv_to_records.rb
  app/models/early_career_payments/dqt_record.rb
  app/models/maths_and_physics/dqt_record.rb
  app/models/student_loans/dqt_record.rb
  lib/dqt/objects/teacher.rb
  spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/lib/dqt/objects/teacher_spec.rb
  spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
  spec/models/early_career_payments/dqt_record_for_subject_code_returned_as_subject_spec.rb
  spec/models/early_career_payments/dqt_record_spec.rb
  spec/support/dqt_helpers.rb
Labels: ruby

#1792 [story/ECP-1288] - Add ITT Subject and ITT Subject Codes to task notes for DqT automation
  CHANGELOG.md
  app/models/automated_checks/claim_verifiers/qualifications.rb
  app/models/automated_checks/dqt_report_csv_to_records.rb
  app/models/early_career_payments/dqt_record.rb
  app/models/maths_and_physics/dqt_record.rb
  app/models/student_loans/dqt_record.rb
  lib/dqt/objects/teacher.rb
  spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/lib/dqt/objects/teacher_spec.rb
  spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
  spec/models/early_career_payments/dqt_record_for_subject_code_returned_as_subject_spec.rb
  spec/models/early_career_payments/dqt_record_spec.rb
  spec/support/dqt_helpers.rb
Labels: enhancement, ruby

#1794 [story/ECP-1355] - Add DqT Qualificaion matching status to admin view claims index page
  CHANGELOG.md
  app/views/admin/claims/index.html.erb
Labels: enhancement, ruby

#1793 [story/ECP-1347] - Use qts award date for qualification matching for QTS/OTT/EEA/NI/Scotland
  CHANGELOG.md
  app/models/early_career_payments/dqt_record.rb
  spec/models/early_career_payments/dqt_record_spec.rb
Labels: enhancement, ruby

#1795 [task/ECP-1357] - Fix deprecation warning - Selenium
  spec/support/capybara.rb
Labels: ruby

#1796 [story/ECP-1339] - Change static email content for OTP email verification to use the GOVUK notify OTP template
  CHANGELOG.md
  app/helpers/early_career_payments_helper.rb
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  app/mailers/reminder_mailer.rb
  spec/features/changing_answers_spec.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/maths_and_physics_claim_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/mailers/claim_mailer_spec.rb
  spec/mailers/previews/claim_mailer_preview.rb
  spec/support/feature_helpers.rb
Labels: enhancement, ruby

#1799 [bug/ECP-1348] - Fix incorrect date/time on manual checks
  CHANGELOG.md
  app/views/admin/tasks/_task_outcome.html.erb
  spec/features/admin_claim_check_spec.rb
Labels: bug, ruby

#1803 [story/ECP-1354] - Add matching against DqT API subject names return while subject codes not available
  CHANGELOG.md
  app/models/early_career_payments/dqt_record.rb
  lib/dqt/objects/teacher.rb
  spec/models/early_career_payments/dqt_record_spec.rb
Labels: enhancement, ruby

#1805 [story/ECP-1352] - Fix street names and numbers for Cantium Data extract
  CHANGELOG.md
  app/controllers/concerns/address_details.rb
  app/models/payroll/payment_csv_row.rb
  app/views/claims/select_home_address.html.erb
  spec/models/payroll/payment_csv_row_spec.rb
Labels: enhancement, ruby

#1820 [story/ECP-891] - Add DqT automation notes to task confirmation screens - qualifications task
  CHANGELOG.md
  app/controllers/admin/tasks_controller.rb
  app/models/claim.rb
  app/models/reminder.rb
  app/views/admin/notes/_note.html.erb
  app/views/admin/notes/index.html.erb
  app/views/admin/tasks/_form.html.erb
  app/views/admin/tasks/_notes.html.erb
  app/views/admin/tasks/_task_outcome.html.erb
  app/views/admin/tasks/qualifications.html.erb
  spec/features/admin_checks_early_career_payments_claim_spec.rb
  spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
Labels: enhancement, ruby

#1815 [story/ECP-1370] - Change static email content for 'Claim approved' to use the GOVUK notify templates
  CHANGELOG.md
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  spec/features/admin_claim_check_spec.rb
  spec/mailers/claim_mailer_spec.rb
Labels: enhancement, ruby

#1821 [story/ECP-1372] - Change static email content for claim 3 week follow-up to use the GOVUK notify templates
  CHANGELOG.md
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  spec/mailers/claim_mailer_spec.rb
Labels: enhancement, ruby

#1824 [story/ECP-1374] - Change static email content for ECP Reminders - application window open to use the GOVUK notify template
  CHANGELOG.md
  app/mailers/application_mailer.rb
  app/mailers/reminder_mailer.rb
  spec/jobs/send_reminder_emails_job_spec.rb
Labels: enhancement, ruby

#1825 [story/ECP-1375] - Change static email content for ECP reminders - set up confirmation to use the GOVUK notify template
  CHANGELOG.md
  app/mailers/application_mailer.rb
  app/mailers/reminder_mailer.rb
  spec/features/reminders_spec.rb
Labels: enhancement, ruby

#1819 [story/ECP-1371] - Change static email content for 'Claim rejected' to use the GOVUK notify templates
  CHANGELOG.md
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  spec/features/admin_claim_check_spec.rb
  spec/mailers/claim_mailer_spec.rb
Labels: enhancement, ruby
