Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-08, with the labels that each got.

#3034 CAPT-1531 Notify emails
  app/helpers/admin/claims_helper.rb
  app/models/decision.rb
  app/models/policies/early_career_payments.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/international_relocation_payments.rb
  app/models/policies/levelling_up_premium_payments.rb
  app/models/policies/student_loans.rb
  app/views/admin/decisions/_decision_form.html.erb
  config/locales/en.yml
  spec/factories/decisions.rb
  spec/helpers/claim_mailer_helper_spec.rb
  spec/mailers/claim_mailer_spec.rb
  spec/models/decision_spec.rb
Labels: deploy

#3047 [LUPEYALPHA-583] FE claim confirmation page
  app/views/further_education_payments/submissions/show.html.erb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy

#3043 [LUPEYALPHA-593] Update copy for FE information provided
  app/views/further_education_payments/claims/information_provided.html.erb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy

#3032 [LUPEYALPHA-787] Add back links to FE inelgible screens
  app/views/further_education_payments/claims/ineligible.html.erb
  spec/features/further_education_payments/ineligible_paths_spec.rb
Labels: deploy

#3044 [LUPEYALPHA-798] Update copy for FE select provision
  app/views/further_education_payments/claims/select_provision.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/forms/journeys/further_education_payments/select_provision_form_spec.rb
Labels: deploy

#3048 [LUPEYALPHA-763] EY Declaration of consent page
  app/forms/journeys/early_years_payment/provider/claim_submission_form.rb
  app/forms/journeys/early_years_payment/provider/consent_form.rb
  app/models/journeys/early_years_payment/provider.rb
  app/models/journeys/early_years_payment/provider/session_answers.rb
  app/models/journeys/early_years_payment/provider/slug_sequence.rb
  app/views/early_years_payment/provider/claims/consent.html.erb
  app/views/early_years_payment/provider/claims/current_nursery.html.erb
  app/views/early_years_payment/provider/landing_page.html.erb
  config/locales/en.yml
  spec/factories/journeys/early_years_payment/provider/session.rb
  spec/features/early_years_payment/provider/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/consent_form_spec.rb
Labels: deploy

#3055 [LUPEYALPHA-705] Teacher ID in Journey config admin area
  app/models/journeys/configuration.rb
  app/views/admin/journey_configurations/edit.html.erb
  spec/features/admin/admin_access_spec.rb
  spec/features/admin/admin_amend_claim_spec.rb
  spec/features/admin/admin_amend_decision_spec.rb
  spec/features/admin/admin_checks_early_career_payments_claim_spec.rb
  spec/features/admin/admin_checks_levelling_up_premium_payments_claim_spec.rb
  spec/features/admin/admin_checks_student_loan_claim_spec.rb
  spec/features/admin/admin_claim_allocation_and_deallocation_spec.rb
  spec/features/admin/admin_claim_allocation_spec.rb
  spec/features/admin/admin_claim_check_spec.rb
  spec/features/admin/admin_claim_notes_spec.rb
  spec/features/admin/admin_claim_payroll_details_task_spec.rb
  spec/features/admin/admin_claim_support_tickets_spec.rb
  spec/features/admin/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/features/admin/admin_claim_tasks_update_with_dqt_csv_spec.rb
  spec/features/admin/admin_claim_with_inconsistent_payroll_information_spec.rb
  spec/features/admin/admin_claim_with_matching_details_spec.rb
  spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
  spec/features/admin/admin_claim_without_personal_data_spec.rb
  spec/features/admin/admin_claim_without_verified_identity_spec.rb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/features/admin/admin_claims_pagination_spec.rb
  spec/features/admin/admin_configure_services_spec.rb
  spec/features/admin/admin_data_report_request_spec.rb
  spec/features/admin/admin_edit_claim_spec.rb
  spec/features/admin/admin_hold_claim_spec.rb
  spec/features/admin/admin_manage_lupp_school_awards_spec.rb
  spec/features/admin/admin_payroll_run_download_spec.rb
  spec/features/admin/admin_payroll_runs_spec.rb
  spec/features/admin/admin_reject_claim_spec.rb
  spec/features/admin/admin_search_spec.rb
  spec/features/admin/admin_sessions_spec.rb
  spec/features/admin/admin_stats_spec.rb
  spec/features/admin/admin_timeout_spec.rb
  spec/features/admin/admin_view_claim_spec.rb
  spec/features/admin/admin_views_completed_claim_spec.rb
Labels: deploy

#3060 [LUPEYALPHA-831] Copy update: FE ineligible pages, action links
  app/views/further_education_payments/claims/_ineligible_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
  app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
  app/views/further_education_payments/claims/_ineligible_less_than_half_hours_teaching_eligible_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_must_at_least_half_hours_teaching_fe.html.erb
  app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
  app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
  app/views/further_education_payments/claims/_ineligible_subject.html.erb
  app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
  app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
  app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
Labels: deploy

#3064 [LUPEYALPHA-816] FE copy update: tweak building course name
  app/forms/journeys/further_education_payments/building_construction_courses_form.rb
  app/models/journeys/further_education_payments/courses_helper.rb
  config/locales/en.yml
  spec/forms/journeys/further_education_payments/building_construction_courses_form_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy

#3059 support validating OTP without a generated_at time and with a specified secret
  lib/one_time_password/base.rb
  lib/one_time_password/generator.rb
  lib/one_time_password/validator.rb
  spec/features/one_time_password_spec.rb
  spec/lib/one_time_password/generator_spec.rb
  spec/lib/one_time_password/validator_spec.rb
Labels: deploy

#3067 [LUPEYALPHA-817] FE copy update for chemistry courses
  app/forms/journeys/further_education_payments/chemistry_courses_form.rb
  config/locales/en.yml
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy

#3068 [LUPEYALPHA-830] Update FE physics courses
  app/forms/journeys/further_education_payments/physics_courses_form.rb
  config/locales/en.yml
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy

#3069 [LUPEYALPHA-828] Tweak FE engineering courses
  app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
  app/models/journeys/further_education_payments/courses_helper.rb
  config/locales/en.yml
  spec/forms/journeys/further_education_payments/engineering_manufacturing_courses_form_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy

#3075 [LUPEYALPHA-829] Tweak FE maths courses
  app/forms/journeys/further_education_payments/maths_courses_form.rb
  app/models/journeys/further_education_payments/courses_helper.rb
  config/locales/en.yml
  spec/features/further_education_payments/happy_path_spec.rb
  spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy

#3076 [LUPEYALPHA-597] One login header + sign out
  .env.development
  .env.test
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/button_to.scss
  app/controllers/deauth_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/forms/sign_in_form.rb
  app/models/journeys/session_answers.rb
  app/views/claims/_sign_in.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_one_login_header.html.erb
  config/routes.rb
  package.json
  spec/forms/sign_in_form_spec.rb
  spec/requests/deauth_spec.rb
  yarn.lock
Labels: deploy

#3086 add citext to azure extensions
  terraform/application/database.tf
Labels: deploy

#3084 [LUPEYALPHA-842] EY send another link
  app/controllers/claims_form_callbacks.rb
  app/models/journeys/early_years_payment/provider/start.rb
  app/models/journeys/page_sequence.rb
  app/views/early_years_payment/provider/start/claims/check_your_email.html.erb
  spec/features/early_years_payment/provider/start/happy_path_spec.rb
Labels: deploy

#3092 [LUPEYALPHA-765] EY - Who are you making this claim for?
  app/forms/journeys/early_years_payment/provider/authenticated/claimant_name_form.rb
  app/forms/personal_details_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/models/name_format_validator.rb
  app/views/early_years_payment/provider/authenticated/claims/claimant_name.html.erb
  app/views/early_years_payment/provider/authenticated/claims/start_date.html.erb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claimant_name_form_spec.rb
Labels: deploy

#3102 [LUPEYALPHA-770] EY PAYE reference
  app/forms/journeys/early_years_payment/provider/authenticated/paye_reference_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/views/early_years_payment/provider/authenticated/claims/paye_reference.html.erb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/paye_reference_form_spec.rb
Labels: deploy

#3099 [LUPEYALPHA-766] EY start date
  app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
  app/views/early_years_payment/provider/authenticated/claims/start_date.html.erb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/start_date_form_spec.rb
Labels: deploy

#3096 [LUPEYALPHA-767] confirm spends most of the time working with children
  app/forms/journeys/early_years_payment/provider/authenticated/child_facing_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
  app/views/early_years_payment/provider/authenticated/claims/returner.html.erb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/child_facing_form_spec.rb
Labels: deploy

#3108 Update terraform providers
  terraform/application/terraform.tf
  terraform/domains/environment_domains/terraform.tf
  terraform/domains/infrastructure/terraform.tf
Labels: devops, deploy

#3101 [LUPEYALPHA-768] Returner/first job screen
  app/forms/journeys/early_years_payment/provider/authenticated/returner_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/views/early_years_payment/provider/authenticated/claims/current_nursery.html.erb
  app/views/early_years_payment/provider/authenticated/claims/employee_email.html.erb
  app/views/early_years_payment/provider/authenticated/claims/returner.html.erb
  config/initializers/date_formats.rb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/returner_form_spec.rb
Labels: deploy

#3105 [LUPEYALPHA-769] practitioner email address
  app/forms/journeys/early_years_payment/provider/authenticated/employee_email_form.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
  app/views/early_years_payment/provider/authenticated/claims/check_your_answers.html.erb
  app/views/early_years_payment/provider/authenticated/claims/employee_email.html.erb
  config/locales/en.yml
  spec/features/admin/admin_timeout_spec.rb
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/employee_email_form_spec.rb
Labels: deploy

#3109 One Login save UID + check it
  app/controllers/omniauth_callbacks_controller.rb
  app/models/journeys/session_answers.rb
  app/models/one_login/core_identity_validator.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
Labels: deploy

#3110 Start date validations
  app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/start_date_form_spec.rb
Labels: deploy

#3121 Add snyk scan to build workflow
  .github/workflows/build_and_deploy.yml
Labels: devops

#3111 [LUPEYALPHA-771] check your answers
  app/controllers/claims_controller.rb
  app/controllers/claims_form_callbacks.rb
  app/controllers/concerns/claim_submission.rb
  app/controllers/submissions_controller.rb
  app/forms/journeys/early_years_payment/provider/authenticated/check_your_answers_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
  app/mailers/application_mailer.rb
  app/models/claim.rb
  app/models/journeys/early_years_payment/provider/authenticated.rb
  app/models/journeys/early_years_payment/provider/authenticated/answers_presenter.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/views/early_years_payment/provider/authenticated/claims/check_your_answers.html.erb
  app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
  app/views/early_years_payment/provider/authenticated/claims/consent.html.erb
  app/views/early_years_payment/provider/authenticated/claims/employee_email.html.erb
  app/views/early_years_payment/provider/authenticated/claims/paye_reference.html.erb
  app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/locales/en.yml
  db/migrate/20240821110005_add_answer_fields_to_claims.rb
  db/migrate/20240821110027_add_answer_fields_to_ey_eligibilities.rb
  db/schema.rb
  spec/factories/journeys/early_years_payment/provider/authenticated/early_years_payment_provider_authenticated_answers.rb
  spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/features/early_years_payment/provider/authenticated/submitter_name_omitted_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/check_your_answers_form_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
  spec/models/claim_spec.rb
  spec/models/journeys/early_years_payment/provider/authenticated/answers_presenter_spec.rb
  spec/support/steps/eligible_ey_journey_authenticated.rb
Labels: deploy

#3119 [LUPEYALPHA-882] Change checkbox to radio buttons for child-facing page
  app/forms/journeys/early_years_payment/provider/authenticated/child_facing_form.rb
  app/models/policies/early_years_payments/policy_eligibility_checker.rb
  app/views/early_years_payment/provider/authenticated/claims/_ineligibility_not_child_facing_enough.html.erb
  app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
  config/locales/en.yml
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/features/early_years_payment/provider/authenticated/not_child_facing_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/child_facing_form_spec.rb
  spec/support/steps/eligible_ey_journey_authenticated.rb
Labels: deploy

#3115 LUPEYALPHA-838 - send verification request to provider
  app/forms/journeys/further_education_payments/claim_submission_form.rb
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  app/models/journeys/further_education_payments/provider/slug_sequence.rb
  app/models/policies/further_education_payments/eligibility.rb
  spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
Labels: deploy

#3122 [LUPEYALPHA-947] Update FE provision search copy
  app/views/further_education_payments/claims/further_education_provision_search.html.erb
Labels: deploy

#3120 [LUPEYALPHA-848] Add FE claimant email templates
  app/mailers/application_mailer.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy

#3127 [LUPEYALPHA-948] FE ineligible less than 2.5h - content update
  app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
Labels: deploy

#3123 [LUPEYALPHA-949] content update - remove hourly paid
  app/forms/journeys/further_education_payments/contract_type_form.rb
Labels: deploy

#3124 [LUPEYALPHA-950] teaching-hours-per-week page - content update
  config/locales/en.yml
  spec/requests/admin_tps_data_upload_spec.rb
Labels: deploy

#3125 [LUPEYALPHA-951] teaching qualification - hint content update
  app/views/further_education_payments/claims/teaching_qualification.html.erb
  config/locales/en.yml
Labels: deploy

#3116 fe provider dsi bypass
  app/controllers/omniauth_callbacks_controller.rb
  app/forms/journeys/further_education_payments/provider/omniauth_callback_form.rb
  app/views/further_education_payments/provider/claims/_dfe_sign_in_bypass_form.html.erb
  app/views/further_education_payments/provider/claims/sign_in.html.erb
  config/initializers/omniauth.rb
Labels: deploy

#3133 [LUPEYALPHA-704] FE reminders
  app/controllers/reminders_controller.rb
  app/forms/reminders/confirmation_form.rb
  app/forms/reminders/email_verification_form.rb
  app/forms/reminders/personal_details_form.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/reminders/slug_sequence.rb
  app/views/further_education_payments/submissions/show.html.erb
  app/views/reminders/confirmation.html.erb
  app/views/reminders/email_verification.html.erb
  app/views/reminders/personal_details.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy
