Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-12, with the labels that each got.

#3438 [CAPT-1631] If one eligible_itt_subject show better error msg
  app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
  spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
Labels: deploy, business reviewed

#3442 [CAPT-1999] Rails 8
  Gemfile
  Gemfile.lock
  app/models/student_loans_data_importer.rb
  config/application.rb
Labels: deploy

#3448 Patch rails_semantic_logger for rails 8
  Gemfile.lock
  config/initializers/rails_semantic_logger_8_monkeypatch.rb
  db/schema.rb
Labels: deploy

#3451 [CAPT-2047] Add EY serializer for admin data report
  app/models/claim/data_report_request.rb
  spec/models/claim/data_report_request_spec.rb
Labels: deploy

#3455 [2158] Replace terrafile
  .gitignore
  Makefile
  global_config/domains.sh
  global_config/production.sh
  global_config/review.sh
  global_config/test.sh
  terraform/application/config/production_Terrafile
  terraform/application/config/review_Terrafile
  terraform/application/config/test_Terrafile
  terraform/domains/environment_domains/config/production_Terrafile
  terraform/domains/environment_domains/config/test_Terrafile
  terraform/domains/infrastructure/config/zones_Terrafile
Labels: devops

#3415 CAPT 1995/remove ecp
  app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
  app/forms/journeys/additional_payments_for_teaching/itt_academic_year_form.rb
  app/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form.rb
  app/helpers/claims/itt_subject_helper.rb
  app/models/academic_year.rb
  app/models/concerns/eligibility_checkable.rb
  app/models/concerns/policies/early_career_payments/eligible.rb
  app/models/concerns/policies/levelling_up_premium_payments/eligible.rb
  app/models/journeys/additional_payments_for_teaching.rb
  app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
  app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
  app/models/journeys/eligibility_checker.rb
  app/models/journeys/page_sequence.rb
  app/models/policies/early_career_payments.rb
  app/models/policies/early_career_payments/dqt_record.rb
  app/models/policies/early_career_payments/eligibility.rb
  app/models/policies/early_career_payments/policy_eligibility_checker.rb
  app/models/policies/levelling_up_premium_payments.rb
  app/models/policies/levelling_up_premium_payments/dqt_record.rb
  app/models/policies/levelling_up_premium_payments/policy_eligibility_checker.rb
  app/views/additional_payments/claims/_ineligibility_ecp_only_ecp_closed.html.erb
  app/views/additional_payments/claims/eligible_degree_subject.html.erb
  lib/ineligibility_reason_checker.rb
  lib/journey_subject_eligibility_checker.rb
  spec/factories/policies/early_career_payments/eligibilities.rb
  spec/features/admin/admin_claim_tasks_update_with_dqt_api_spec.rb
  spec/features/combined_teacher_claim_journey_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
  spec/features/ineligible_student_loans_claims_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
  spec/helpers/claims/itt_subject_helper_spec.rb
  spec/helpers/early_career_payments_helper_spec.rb
  spec/lib/ineligibility_reason_checker_spec.rb
  spec/lib/journey_subject_eligibility_checker_spec.rb
  spec/models/early_career_payments_spec.rb
  spec/models/journeys/additional_payments_for_teaching_spec.rb
  spec/models/levelling_up_premium_payments_spec.rb
  spec/models/policies/early_career_payments/dqt_record_spec.rb
  spec/models/policies/early_career_payments/eligibility_spec.rb
  spec/models/policies/levelling_up_premium_payments/dqt_record_spec.rb
Labels: deploy

#3465 Check name contains at least one letter
  app/models/name_format_validator.rb
  spec/forms/personal_details_form_spec.rb
Labels: deploy

#3470 Fix deadline warning tag
  app/views/admin/tasks/_claim_summary_international_relocation_payments.html.erb
Labels: deploy

#3466 Add stricter address validations
  app/forms/address_form.rb
  spec/forms/address_form_spec.rb
Labels: deploy
