Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-07, with the labels that each got.

#2921 [LUPEYALPHA-546] Add FE contract type
  app/forms/journeys/further_education_payments/contract_type_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/views/further_education_payments/claims/contract_type.html.erb
  config/locales/en.yml
  spec/factories/journeys/further_education_payments/session_answers.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
Labels: deploy

#2943 Add eligibility check for contract start date
  app/models/academic_year.rb
  app/models/policies/international_relocation_payments/eligibility.rb
  app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
  spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
  spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
  spec/models/academic_year_spec.rb
  spec/models/policies/international_relocation_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#2940 [1750] DNS domains infrastructure
  .gitignore
  Makefile
  global_config/domains.sh
  terraform/domains/infrastructure/config/zones.tfvars.json
  terraform/domains/infrastructure/config/zones_Terrafile
  terraform/domains/infrastructure/main.tf
  terraform/domains/infrastructure/terraform.tf
  terraform/domains/infrastructure/variables.tf
Labels: devops

#2924 [LUPEYALPHA-550] Add academic start year form for FE journey
  app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/views/further_education_payments/claims/academic_year_in_further_education.html.erb
  app/views/further_education_payments/claims/further_education_teaching_start_year.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
Labels: deploy

#2927 [LUPEYALPHA-549] Add teaching hours per week to FE journey
  app/forms/journeys/further_education_payments/teaching_hours_per_week_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/views/further_education_payments/claims/teaching_hours_per_week.html.erb
  config/locales/en.yml
  spec/factories/journeys/further_education_payments/further_education_payments_answers.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/forms/journeys/further_education_payments/teaching_hours_per_week_form_spec.rb
Labels: deploy

#2947 [LUPEYALPHA-615] FE journey handle ineligible as lack teaching
  app/forms/journeys/further_education_payments/ineligible_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/eligibility_checker.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
  app/views/further_education_payments/claims/ineligible.html.erb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#2950 [LUPEYALPHA-557] Add eligible page to FE journey
  app/forms/journeys/further_education_payments/check_your_answers_form.rb
  app/forms/journeys/further_education_payments/eligible_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/views/further_education_payments/claims/check_your_answers.html.erb
  app/views/further_education_payments/claims/eligible.html.erb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy

#2953 [1750] DNS configuration for test and production domains
  terraform/domains/environment_domains/config/production.tfvars.json
  terraform/domains/environment_domains/config/production_Terrafile
  terraform/domains/environment_domains/config/test.tfvars.json
  terraform/domains/environment_domains/config/test_Terrafile
  terraform/domains/environment_domains/main.tf
  terraform/domains/environment_domains/terraform.tf
  terraform/domains/environment_domains/variables.tf
Labels: devops

#2967 CAPT 1753/only show state secondary schools
  app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
  app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
  app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
  spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
  spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
  spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
  spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
  spec/models/policies/international_relocation_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#2972 Add IRP notify templates
  app/mailers/application_mailer.rb
Labels: deploy

#2965 [LUPEYALPHA-547] FE contract type and branching
  app/forms/form.rb
  app/forms/journeys/further_education_payments/contract_type_form.rb
  app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
  app/forms/journeys/further_education_payments/taught_at_least_one_term_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
  app/views/further_education_payments/claims/fixed_term_contract.html.erb
  app/views/further_education_payments/claims/taught_at_least_one_term.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/forms/form_spec.rb
  spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
  spec/forms/journeys/further_education_payments/fixed_term_contract_form_spec.rb
  spec/forms/journeys/further_education_payments/taught_at_least_one_term_form_spec.rb
  spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#2985 IRP review app 4
  app/models/policies/international_relocation_payments/eligibility_admin_answers_presenter.rb
  config/locales/en.yml
  spec/factories/policies/international_relocation_payments/eligibilities.rb
  spec/models/policies/international_relocation_payments/eligibility_admin_answers_presenter_spec.rb
Labels: Do not merge, deploy

#2984 [LUPEYALPHA-640] Add ineligible state for non recent FE teacher
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
  spec/features/further_education_payments/ineligible_paths_spec.rb
Labels: deploy

#2987 [LUPEYALPHA-645] Add FE ineligible state due to problematic actions
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
  spec/features/further_education_payments/ineligible_paths_spec.rb
Labels: deploy

#2990 [LUPEYALPHA-649] Add ineligible state to FE journey
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
  spec/features/further_education_payments/ineligible_paths_spec.rb
Labels: deploy

#2978 [LUPEYALPHA-551] FE subjects and courses
  app/forms/journeys/further_education_payments/building_construction_courses_form.rb
  app/forms/journeys/further_education_payments/chemistry_courses_form.rb
  app/forms/journeys/further_education_payments/computing_courses_form.rb
  app/forms/journeys/further_education_payments/early_years_courses_form.rb
  app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
  app/forms/journeys/further_education_payments/maths_courses_form.rb
  app/forms/journeys/further_education_payments/physics_courses_form.rb
  app/forms/journeys/further_education_payments/subjects_taught_form.rb
  app/forms/journeys/further_education_payments/teaching_responsibilities_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_subject.html.erb
  app/views/further_education_payments/claims/building_and_construction_courses.html.erb
  app/views/further_education_payments/claims/building_construction_courses.html.erb
  app/views/further_education_payments/claims/chemistry_courses.html.erb
  app/views/further_education_payments/claims/computing_courses.html.erb
  app/views/further_education_payments/claims/early_years_courses.html.erb
  app/views/further_education_payments/claims/engineering_manufacturing_courses.html.erb
  app/views/further_education_payments/claims/maths_courses.html.erb
  app/views/further_education_payments/claims/physics_courses.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/forms/journeys/further_education_payments/building_construction_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/chemistry_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/computing_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/early_years_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/engineering_manufacturing_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/maths_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/physics_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
  spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#3007 [1914] Database restore workflow
  .github/workflows/database_restore.yml
Labels: devops

#3008 [1914] Override backup file name in restore workflow
  .github/workflows/database_restore.yml
Labels: devops

#3000 [1914] Point front door at the new environments on AKS
  terraform/domains/environment_domains/config/production.tfvars.json
  terraform/domains/environment_domains/config/test.tfvars.json
Labels: devops

#3006 [LUPEYALPHA-551] Admins can upload + download eligible FE providers
  app/controllers/admin/eligible_fe_providers_controller.rb
  app/controllers/admin/journey_configurations_controller.rb
  app/forms/admin/eligible_fe_providers_form.rb
  app/models/eligible_fe_provider.rb
  app/models/eligible_fe_providers_importer.rb
  app/views/admin/eligible_fe_providers/new.html.erb
  app/views/admin/journey_configurations/_edit_additional_payments.html.erb
  app/views/admin/journey_configurations/_edit_further_education_payments.html.erb
  app/views/admin/journey_configurations/edit.html.erb
  app/views/layouts/admin.html.erb
  config/analytics.yml
  config/routes.rb
  db/migrate/20240710080536_create_eligible_fe_providers.rb
  db/schema.rb
  lib/csv_importer/base.rb
  spec/factories/eligible_fe_providers.rb
  spec/features/admin/eligible_fe_providers_spec.rb
  spec/features/further_education_payments/college_not_found_spec.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/models/eligible_fe_providers_importer_spec.rb
  spec/support/steps/journey_configuration.rb
Labels: deploy

#3013 Enqueue school import job when seeding
  db/seeds.rb
Labels: deploy

#2989 Fe hours teaching eligible subjects
  app/forms/form_helpers.rb
  app/forms/journeys/further_education_payments/building_construction_courses_form.rb
  app/forms/journeys/further_education_payments/chemistry_courses_form.rb
  app/forms/journeys/further_education_payments/computing_courses_form.rb
  app/forms/journeys/further_education_payments/early_years_courses_form.rb
  app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
  app/forms/journeys/further_education_payments/hours_teaching_eligible_subjects_form.rb
  app/forms/journeys/further_education_payments/maths_courses_form.rb
  app/forms/journeys/further_education_payments/physics_courses_form.rb
  app/forms/journeys/further_education_payments/subjects_taught_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/courses_helper.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
  app/views/further_education_payments/claims/teaching_courses.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/forms/form_spec.rb
  spec/forms/journeys/further_education_payments/hours_teaching_eligible_subjects_form_spec.rb
Labels: deploy

#3014 [LUPEYALPHA-652] FE ineligible provider selected
  app/assets/javascripts/components/college_search.js.erb
  app/forms/journeys/further_education_payments/further_education_provision_search_form.rb
  app/forms/journeys/further_education_payments/select_provision_form.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/further_education_payments/policy_eligibility_checker.rb
  app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
  app/views/further_education_payments/claims/further_education_provision_search.html.erb
  app/views/further_education_payments/claims/select_provision.html.erb
  config/locales/en.yml
  db/seeds.rb
  spec/factories/schools.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/fixtures/files/eligible_fe_providers.csv
  spec/forms/journeys/further_education_payments/further_education_provision_search_form_spec.rb
  spec/forms/journeys/further_education_payments/select_provision_form_spec.rb
  spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
Labels: deploy

#3021 [LUPEYALPHA-653] FE award amount
  app/forms/journeys/further_education_payments/eligible_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/school.rb
  app/views/further_education_payments/claims/eligible.html.erb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/models/journeys/further_education_payments/session_answers_spec.rb
Labels: deploy

#3033 [1881] Ship production logs to Logit.io
  terraform/application/config/production.tfvars.json
Labels: devops

#3026 [LUPEYALPHA-760] EY scaffolding + landing page
  .github/workflows/build_and_deploy.yml
  app/models/journeys.rb
  app/models/journeys/early_years_payment/provider.rb
  app/models/journeys/early_years_payment/provider/eligibility_checker.rb
  app/models/journeys/early_years_payment/provider/session.rb
  app/models/journeys/early_years_payment/provider/session_answers.rb
  app/models/journeys/early_years_payment/provider/session_answers_type.rb
  app/models/journeys/early_years_payment/provider/slug_sequence.rb
  app/models/policies/early_years_payment.rb
  app/models/policies/early_years_payment/eligibility.rb
  app/models/policies/early_years_payment/policy_eligibility_checker.rb
  app/views/early_years_payment/provider/landing_page.html.erb
  config/analytics.yml
  config/locales/en.yml
  db/migrate/20240724092519_create_early_years_payment_eligibilities.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/journey_configurations.rb
  spec/features/early_years_payment/provider/happy_path_spec.rb
  spec/models/journeys_spec.rb
  spec/support/steps/journey_configuration.rb
Labels: deploy

#3035 CAPT-1773 remove 30min timeout
  app/controllers/base_public_controller.rb
  app/controllers/claims_controller.rb
  app/controllers/claims_form_callbacks.rb
  app/controllers/concerns/claim_session_timeout.rb
  app/controllers/concerns/journey_concern.rb
  app/controllers/concerns/session_management.rb
  app/controllers/journeys/additional_payments_for_teaching/reminders_controller.rb
  app/controllers/journeys/additional_payments_for_teaching/reminders_form_callbacks.rb
  app/controllers/sessions_controller.rb
  app/models/journeys/session_answers.rb
  app/views/claims/no_address_found.html.erb
  app/views/claims/timeout.html.erb
  app/views/layouts/application.html.erb
  app/views/static_pages/cookies.html.erb
  config/routes.rb
  spec/features/changing_answers_spec.rb
  spec/features/timeout_spec.rb
  spec/requests/claims_spec.rb
  spec/requests/sessions_spec.rb
  spec/requests/submissions_spec.rb
  spec/requests/timeout_spec.rb
Labels: deploy
