Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-09, with the labels that each got.

#3132 Update error message copy
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/views/further_education_payments/provider/claims/verify_claim.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Labels: deploy

#3130 [LUPEYALPHA-935] Update error messages in FE claimant journey
  app/forms/journeys/further_education_payments/contract_type_form.rb
  app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
  app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
  app/forms/journeys/further_education_payments/teaching_hours_per_week_form.rb
  app/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form.rb
  app/views/further_education_payments/claims/fixed_term_contract.html.erb
  config/locales/en.yml
  spec/forms/journeys/further_education_payments/building_construction_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/chemistry_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/computing_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
  spec/forms/journeys/further_education_payments/early_years_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/engineering_manufacturing_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/fixed_term_contract_form_spec.rb
  spec/forms/journeys/further_education_payments/further_education_provision_search_form_spec.rb
  spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
  spec/forms/journeys/further_education_payments/maths_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/physics_courses_form_spec.rb
  spec/forms/journeys/further_education_payments/select_provision_form_spec.rb
  spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
  spec/forms/journeys/further_education_payments/teaching_hours_per_week_form_spec.rb
  spec/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form_spec.rb
  spec/forms/journeys/further_education_payments/teaching_qualification_form_spec.rb
Labels: deploy

#3138 [LUPEYALPHA-934] FE LUP name change
  app/views/further_education_payments/claims/_ineligible_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
  app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
  app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
  app/views/further_education_payments/claims/_ineligible_less_than_half_hours_teaching_eligible_courses.html.erb
  app/views/further_education_payments/claims/_ineligible_must_at_least_half_hours_teaching_fe.html.erb
  app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
  app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
  app/views/further_education_payments/claims/_ineligible_subject.html.erb
  app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
  app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
  app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
  app/views/further_education_payments/claims/eligible.html.erb
  app/views/further_education_payments/claims/information_provided.html.erb
  app/views/further_education_payments/claims/teaching_responsibilities.html.erb
  app/views/further_education_payments/landing_page.html.erb
  app/views/further_education_payments/provider/claims/_unauthorised_already_verified.html.erb
  app/views/further_education_payments/provider/claims/_unauthorised_organisation_mismatch.html.erb
  app/views/further_education_payments/provider/claims/complete.html.erb
  app/views/further_education_payments/provider/claims/sign_in.html.erb
  app/views/further_education_payments/provider/landing_page.html.erb
  app/views/further_education_payments/submissions/show.html.erb
  config/locales/en.yml
  spec/features/admin/admin_configure_services_spec.rb
  spec/features/admin/eligible_fe_providers_spec.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
Labels: deploy

#3142 [LUPEYALPHA-846] content updates
  app/views/further_education_payments/claims/information_provided.html.erb
  app/views/further_education_payments/submissions/show.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
Labels: deploy

#3131 admin provider verification task
  app/forms/journeys/further_education_payments/provider/omniauth_callback_form.rb
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/models/automated_checks/claim_verifiers/provider_verification.rb
  app/models/base_policy.rb
  app/models/claim_checking_tasks.rb
  app/models/journeys/further_education_payments/provider/session_answers.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  app/models/task.rb
  app/views/admin/tasks/provider_verification.html.erb
  app/views/further_education_payments/provider/claims/_dfe_sign_in_bypass_form.html.erb
  config/locales/en.yml
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
  spec/forms/journeys/further_education_payments/provider/omniauth_callback_form_spec.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
  spec/models/automated_checks/claim_verifiers/provider_verification_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy

#3145 Don't email provider for duplicate claims
  app/forms/journeys/further_education_payments/claim_submission_form.rb
  app/models/policies/further_education_payments.rb
  config/analytics.yml
  db/migrate/20240904105917_add_flagged_as_duplicate_to_further_education_payments_eligibilities.rb
  db/schema.rb
  spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
Labels: deploy

#3128 Add heartbeat monitor for statuscake
  README.md
  app/jobs/heartbeat_job.rb
  terraform/application/application.tf
  terraform/application/statuscake.tf
  terraform/application/variables.tf
Labels: deploy

#3151 [LUPEYALPHA-1001] FE content updates
  app/models/policies/further_education_payments.rb
  app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
  app/views/further_education_payments/claims/further_education_provision_search.html.erb
  app/views/further_education_payments/landing_page.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/ineligible_paths_spec.rb
Labels: deploy

#3148 [LUPALPHA-997] resend provider verification email
  app/controllers/admin/further_education_payments/provider_verification_emails_controller.rb
  app/views/admin/tasks/provider_verification.html.erb
  config/routes.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
Labels: deploy

#3139 Provider confirmation email
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
  spec/support/have_received_email_matcher.rb
Labels: deploy

#3156 Add rejection reasons for FE claims
  app/models/policies/further_education_payments.rb
  config/locales/en.yml
Labels: deploy

#3163 Show type of contract claimant selected
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/models/policies/further_education_payments/eligibility.rb
  app/views/further_education_payments/provider/claims/verify_claim.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Labels: deploy

#3150 [LUPEYALPHA-964] Claim Summary for FE
  app/helpers/admin/claim_summary_helper.rb
  app/views/admin/amendments/index.html.erb
  app/views/admin/decisions/new.html.erb
  app/views/admin/notes/index.html.erb
  app/views/admin/payments/index.html.erb
  app/views/admin/tasks/_claim_summary_further_education_payments.html.erb
  app/views/admin/tasks/arrival_date.html.erb
  app/views/admin/tasks/census_subjects_taught.html.erb
  app/views/admin/tasks/employment.html.erb
  app/views/admin/tasks/employment_contract.html.erb
  app/views/admin/tasks/employment_start.html.erb
  app/views/admin/tasks/identity_confirmation.html.erb
  app/views/admin/tasks/index.html.erb
  app/views/admin/tasks/induction_confirmation.erb
  app/views/admin/tasks/matching_details.html.erb
  app/views/admin/tasks/payroll_details.html.erb
  app/views/admin/tasks/payroll_gender.html.erb
  app/views/admin/tasks/qualifications.html.erb
  app/views/admin/tasks/student_loan_amount.html.erb
  app/views/admin/tasks/student_loan_plan.html.erb
  app/views/admin/tasks/subject.html.erb
  app/views/admin/tasks/teaching_hours.html.erb
  app/views/admin/tasks/visa.html.erb
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_view_claim_further_education_payments_spec.rb
  spec/features/admin/admin_view_claim_spec.rb
  spec/helpers/admin/claim_summary_helper_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
  spec/support/admin_view_claim_logged_in_with_tid_feature_shared_examples.rb
Labels: deploy

#3155 [LUPEYALPHA-1009] make award amount editable for FE
  app/helpers/admin/amendments_helper.rb
  spec/helpers/admin/amendments_helper_spec.rb
Labels: deploy

#3173 Refactor: Move additional payments journey specific reminder code to journey module
  app/models/claim.rb
  app/models/journeys/additional_payments_for_teaching.rb
  app/models/reminder.rb
  app/views/additional_payments/submissions/show.html.erb
  spec/models/journeys/additional_payments_for_teaching_spec.rb
  spec/models/reminder_spec.rb
Labels: deploy

#3170 LUPEYALPHA-1014: Change email address
  config/locales/en.yml
Labels: deploy

#3165 [LUPEYALPHA-1012] Admin gender task hint
  Gemfile
  Gemfile.lock
  app/views/admin/decisions/_incomplete_tasks.html.erb
  app/views/admin/tasks/index.html.erb
  app/views/admin/tasks/payroll_gender.html.erb
  config/locales/en.yml
  spec/features/admin/admin_claim_payroll_details_task_spec.rb
  spec/features/admin/admin_claim_with_matching_details_spec.rb
  spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
  spec/features/admin/admin_claim_without_verified_identity_spec.rb
  spec/support/admin_checks_feature_shared_examples.rb
Labels: deploy

#3162 Fix the labels on addresses
  app/views/claims/select_home_address.html.erb
  spec/features/auto_populating_home_address_from_postcode_search_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
  spec/features/early_career_payments_claim_spec.rb
  spec/features/tslr_claim_journey_with_teacher_id_check_email_spec.rb
  spec/features/tslr_claim_journey_with_teacher_id_trn_spec.rb
  spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Labels: deploy

#3167 Record who sent the email to the provider
  app/controllers/admin/further_education_payments/provider_verification_emails_controller.rb
  app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  app/views/admin/tasks/_provider_verification_submitted.html.erb
  app/views/admin/tasks/_provider_verification_unsubmitted.html.erb
  app/views/admin/tasks/provider_verification.html.erb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
Labels: deploy

#3172 [LUPEYALPHA-1024] Add survey to FE confirmation page
  app/views/further_education_payments/submissions/show.html.erb
Labels: deploy

#3188 [LUPEYALPHA-1002] Revamp cookies
  README.md
  app/assets/javascripts/application.js
  app/assets/javascripts/components/cookie_banner.js
  app/assets/javascripts/cookie_functions.js
  app/assets/javascripts/google_analytics.js
  app/assets/stylesheets/components/cookie_banner.scss
  app/controllers/cookies_controller.rb
  app/controllers/static_pages_controller.rb
  app/forms/cookies_form.rb
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/shared/_cookie_banner.html.erb
  app/views/static_pages/cookies.html.erb
  app/views/static_pages/cookies_page.html.erb
  config/routes.rb
  spec/features/cookies_spec.rb
  spec/features/early_career_payments/early_career_payments_claim_lupp_ineligible_spec.rb
  spec/features/early_career_payments/early_career_payments_claim_spec.rb
  spec/features/early_career_payments/early_career_payments_eligible_now_reminder_set_spec.rb
  spec/features/early_career_payments/early_career_payments_landing_page_spec.rb
  spec/features/early_career_payments/early_career_payments_trainee_teacher_spec.rb
  spec/features/early_career_payments/eligible_later_early_career_payments_claim_spec.rb
  spec/features/early_career_payments/ineligible_early_career_payments_claims_spec.rb
  spec/features/early_career_payments/ineligible_early_career_payments_in_2022_and_future_years_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_disabled_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_select_claim_school_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_still_teaching_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_trn_spec.rb
  spec/views/layouts/application.html.erb_spec.rb
Labels: deploy

#3178 [LUPEYALPHA-864] Update hint copy on payroll gender question
  app/views/claims/gender.html.erb
Labels: deploy

#3194 [LUPEYALPHA-1002] Update cookie banner for admins
  app/controllers/admin/cookies_controller.rb
  app/controllers/admin/static_pages_controller.rb
  app/views/admin/_cookie_banner.html.erb
  app/views/admin/static_pages/cookies_page.html.erb
  app/views/layouts/admin.html.erb
  app/views/static_pages/_cookies_content.html.erb
  app/views/static_pages/cookies_page.html.erb
  config/routes.rb
  spec/features/admin/cookies_spec.rb
Labels: deploy

#3189 [LUPEYALPHA-1044] Fix missing translation
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  config/locales/en.yml
Labels: deploy

#3181 LUPEYALPHA 991/view full claim
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/helpers/admin/claims_helper.rb
  app/models/policies/further_education_payments/eligibility.rb
  app/models/policies/further_education_payments/eligibility_admin_answers_presenter.rb
  app/views/admin/claims/_answers.html.erb
  app/views/admin/claims/policies/early_career_payments/_claim.html.erb
  app/views/admin/claims/policies/early_years_payments/_claim.html.erb
  app/views/admin/claims/policies/further_education_payments/_claim.html.erb
  app/views/admin/claims/policies/international_relocation_payments/_claim.html.erb
  app/views/admin/claims/policies/levelling_up_premium_payments/_claim.html.erb
  app/views/admin/claims/policies/student_loans/_claim.html.erb
  app/views/admin/claims/show.html.erb
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
  spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Labels: deploy

#3192 [CAPT-1785] Update IRP email address
  app/models/policies/international_relocation_payments.rb
  app/views/get_a_teacher_relocation_payment/landing_page.html.erb
  config/locales/en.yml
Labels: deploy

#3179 [LUPEYALPHA-1011] Update copy for admin FE task questions
  config/locales/en.yml
Labels: Do not merge, deploy

#3177 [LUPEYALPHA-1020] FE provision search errors on no results
  app/forms/journeys/further_education_payments/further_education_provision_search_form.rb
  app/forms/journeys/further_education_payments/select_provision_form.rb
  app/views/further_education_payments/claims/further_education_provision_search.html.erb
  spec/features/further_education_payments/happy_js_path_spec.rb
Labels: deploy

#3197 Rename LUPP policy
  app/models/policies/levelling_up_premium_payments.rb
  app/views/additional_payments/claims/_eligibility_confirmed_multiple.html.erb
  app/views/additional_payments/claims/_eligibility_guidance_levelling_up_premium_payments.html.erb
  app/views/additional_payments/claims/_ineligibility_bad_itt_subject_for_ecp.html.erb
  app/views/additional_payments/claims/_ineligibility_bad_itt_year_for_ecp.html.erb
  app/views/additional_payments/claims/_ineligibility_current_school.html.erb
  app/views/additional_payments/claims/_ineligibility_dqt_data_ineligible.html.erb
  app/views/additional_payments/claims/_ineligibility_ecp_only_induction_not_completed.html.erb
  app/views/additional_payments/claims/_ineligibility_ecp_only_teacher_with_ineligible_itt_year.html.erb
  app/views/additional_payments/claims/_ineligibility_ecp_only_trainee_teacher.html.erb
  app/views/additional_payments/claims/_ineligibility_generic.html.erb
  app/views/additional_payments/claims/_ineligibility_lack_both_valid_itt_subject_and_degree.html.erb
  app/views/additional_payments/claims/_ineligibility_no_ecp_subjects_that_itt_year.html.erb
  app/views/additional_payments/claims/_ineligibility_teacher_with_ineligible_itt_year.html.erb
  app/views/additional_payments/claims/_ineligibility_trainee_in_last_policy_year.html.erb
  app/views/additional_payments/claims/_ineligibility_trainee_teaching_lacking_both_valid_itt_subject_and_degree.html.erb
  app/views/additional_payments/claims/_ineligibility_would_be_eligible_for_both_ecp_and_lup_except_for_insufficient_teaching.html.erb
  app/views/additional_payments/claims/_ineligibility_would_be_eligible_for_ecp_only_except_for_insufficient_teaching.html.erb
  app/views/additional_payments/claims/_ineligibility_would_be_eligible_for_lup_only_except_for_insufficient_teaching.html.erb
  app/views/additional_payments/claims/eligible_later.html.erb
  app/views/additional_payments/claims/future_eligibility.html.erb
  app/views/additional_payments/landing_page.html.erb
  app/views/additional_payments/submissions/show.html.erb
  app/views/admin/journey_configurations/_edit_additional_payments.html.erb
  app/views/admin/journey_configurations/edit.html.erb
  app/views/admin/payroll_runs/show.html.erb
  config/locales/en.yml
  spec/features/admin/admin_claim_allocation_spec.rb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/features/admin/admin_manage_lupp_school_awards_spec.rb
  spec/features/admin/admin_payroll_runs_spec.rb
  spec/features/combined_teacher_claim_journey_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
  spec/features/hmrc_bank_validation_spec.rb
  spec/features/levelling_up_premium_payments_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/claims/show_helper_spec.rb
  spec/mailers/claim_mailer_spec.rb
  spec/models/levelling_up_premium_payments_spec.rb
  spec/models/policies_spec.rb
Labels: deploy

#3171 LUPEYALPHA-995: Configure FE claims to never be sent for QA
  app/models/policies/further_education_payments.rb
Labels: deploy

#3201 [CAPT-1791] admin IRP previous payment task
  app/models/claim_checking_tasks.rb
  app/models/policies/international_relocation_payments/claim_checking_tasks.rb
  app/models/task.rb
  app/views/admin/tasks/previous_payment.html.erb
  config/locales/en.yml
  spec/features/admin/admin_checks_irp_claim_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy, business reviewed

#3180 [LUPEYALPHA-1036] Admin One Login IDV
  app/forms/journeys/further_education_payments/claim_submission_form.rb
  app/models/automated_checks/claim_verifiers/identity.rb
  app/models/base_policy.rb
  app/models/claim.rb
  app/models/policies/further_education_payments.rb
  app/views/admin/tasks/_one_login_idv.html.erb
  app/views/admin/tasks/identity_confirmation.html.erb
  config/locales/en.yml
  spec/factories/claims.rb
  spec/features/admin/tasks/identity_confirmation_spec.rb
  spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
  spec/models/automated_checks/claim_verifiers/identity_spec.rb
Labels: deploy

#3203 [CAPT-1782] Update copy for IRP confirmation screen
  app/views/get_a_teacher_relocation_payment/submissions/show.html.erb
  app/views/submissions/_confirmation.html.erb
Labels: deploy, business reviewed

#3204 [CAPT-1536] Add IRP specific data to admin CSV download
  app/models/claim/data_report_request.rb
  app/models/policies/international_relocation_payments/eligibility.rb
  spec/models/claim/data_report_request_spec.rb
Labels: deploy, business reviewed

#3198 [LUPEYALPHA-1029] admin notes content update
  app/views/admin/notes/_form.html.erb
  app/views/admin/notes/index.html.erb
Labels: deploy

#3209 Fix task links not showing
  app/views/admin/tasks/_provider_verification_unsubmitted.html.erb
  app/views/admin/tasks/provider_verification.html.erb
Labels: deploy

#3183 [LUPEYALPHA-1031] Cope with student loan data with "No data" rows. Remove invalid match logic
  app/models/automated_checks/claim_verifiers/student_loan_plan.rb
  app/models/claim.rb
  app/models/claim_student_loan_details_updater.rb
  app/models/journeys/answers_student_loans_details_updater.rb
  app/models/policies/student_loans/policy_eligibility_checker.rb
  app/models/student_loans_data_presenter.rb
  spec/factories/student_loans_data.rb
  spec/features/admin/upload_slc_data_spec.rb
  spec/features/ineligible_student_loans_claims_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
  spec/models/claim_spec.rb
  spec/models/claim_student_loan_details_updater_spec.rb
  spec/models/student_loans/eligibility_spec.rb
  spec/requests/admin/admin_student_loans_data_upload_spec.rb
  spec/requests/claims_spec.rb
Labels: deploy

#3195 [LUPEYALPHA-1007] content tweak - admin task for payroll gender
  app/views/admin/tasks/payroll_gender.html.erb
  config/locales/en.yml
  spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
Labels: deploy

#3202 [LUPEYALPHA-1006] Claim page updates: "Awaiting provider verification" filter, remove "Qualification status" column.
  app/forms/admin/claims_filter_form.rb
  app/helpers/admin/claims_helper.rb
  app/models/claim.rb
  app/views/admin/claims/index.html.erb
  config/locales/en.yml
  spec/features/admin/admin_claim_allocation_spec.rb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
  spec/models/claim_spec.rb
  spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
  spec/models/policies_spec.rb
Labels: deploy

#3168 [LUPEYALPHA-1010] student loan plan task for FE
  app/controllers/claims_form_callbacks.rb
  app/jobs/student_loan_plan_check_job.rb
  app/models/automated_checks/claim_verifiers/student_loan_plan.rb
  app/models/base_policy.rb
  app/models/claim.rb
  app/models/claim/claims_awaiting_decision_finder.rb
  app/models/journeys/further_education_payments/answers_student_loans_details_updater.rb
  app/models/policies/early_career_payments.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/further_education_payments/claim_checking_tasks.rb
  app/models/policies/levelling_up_premium_payments.rb
  spec/factories/claims.rb
  spec/features/admin/upload_slc_data_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/jobs/student_loan_plan_check_job_spec.rb
  spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
  spec/models/claim/claims_awaiting_decision_finder_spec.rb
  spec/models/claim_checking_tasks_spec.rb
  spec/models/claim_spec.rb
  spec/models/claim_student_loan_details_updater_spec.rb
  spec/requests/admin/admin_student_loans_data_upload_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
  spec/support/steps/student_loan_data.rb
Labels: deploy

#3214 [CAPT-1823] IRP previous residency task
  app/models/claim_checking_tasks.rb
  app/models/policies/international_relocation_payments.rb
  app/models/policies/international_relocation_payments/claim_checking_tasks.rb
  app/models/task.rb
  app/views/admin/tasks/previous_residency.html.erb
  config/locales/en.yml
  spec/mailers/claim_mailer_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy

#3216 [CAPT-1535] IRP copy tweaks
  app/views/get_a_teacher_relocation_payment/claims/ineligible.html.erb
  app/views/get_a_teacher_relocation_payment/landing_page.html.erb
Labels: deploy

#3215 [CAPT-1822] IRP admin task, tweak arrival date
  app/models/policies/international_relocation_payments/admin_tasks_presenter.rb
  config/locales/en.yml
Labels: deploy

#3218 LUPEYALPHA-1065/amend-slas
  app/views/additional_payments/landing_page.html.erb
  app/views/submissions/_confirmation.html.erb
Labels: deploy

#3210 LUPEYALPHA-1059/update-teaching-hours-question
  config/locales/en.yml
  spec/features/admin/admin_claim_further_education_payments_spec.rb
  spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
  spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Labels: deploy

#3225 Move accessibility dates to locales
  app/views/static_pages/accessibility_statement.html.erb
  config/locales/en.yml
Labels: deploy

#3230 Add EY practitioner scaffolding
  app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/forms/journeys/early_years_payment/practitioner/session_form.rb
  app/models/journeys.rb
  app/models/journeys/early_years_payment/practitioner.rb
  app/models/journeys/early_years_payment/practitioner/eligibility_checker.rb
  app/models/journeys/early_years_payment/practitioner/session.rb
  app/models/journeys/early_years_payment/practitioner/session_answers.rb
  app/models/journeys/early_years_payment/practitioner/session_answers_type.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/early_years_payment/practitioner/landing_page.html.erb
  config/locales/en.yml
  db/seeds.rb
  spec/models/journeys_spec.rb
Labels: deploy

#3233 [LUPEYALPHA-982] EY practitioner how-we-use-your-information page
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/early_years_payment/practitioner/claims/find_reference.html.erb
  app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
  app/views/early_years_payment/practitioner/claims/one_login_sign_in.html.erb
  app/views/early_years_payment/practitioner/claims/personal_details.html.erb
  config/locales/en.yml
  spec/factories/journey_configurations.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/support/steps/journey_configuration.rb
Labels: deploy

#3234 [LUPEYALPHA-983] EY practitioner personal details
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/claims/_personal_details_page.html.erb
  app/views/claims/personal_details.html.erb
  app/views/early_years_payment/practitioner/claims/enter_home_address.html.erb
  app/views/early_years_payment/practitioner/claims/find_reference.html.erb
  app/views/early_years_payment/practitioner/claims/one_login_sign_in.html.erb
  app/views/early_years_payment/practitioner/claims/personal_details.html.erb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
Labels: deploy

#3232 Fixes admin matching claims ui
  app/helpers/admin/claims_helper.rb
  app/models/claim/matching_attribute_finder.rb
  app/views/admin/claims/_claims_with_matching_details.html.erb
  spec/features/admin/admin_claim_with_matching_details_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/models/claim/matching_attribute_finder_spec.rb
Labels: deploy

#3239 Allow deleting payroll runs on review apps
  app/controllers/admin/payroll_runs_controller.rb
  app/models/payroll_run.rb
  app/views/admin/payroll_runs/show.html.erb
  config/routes.rb
Labels: deploy

#3235 [LUPEYALPHA-984] EY practitioner enter home address
  app/models/journeys/early_years_payment/practitioner.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/claims/_address_fields.html.erb
  app/views/claims/address.html.erb
  app/views/early_years_payment/practitioner/claims/email_address.html.erb
  app/views/early_years_payment/practitioner/claims/enter_home_address.html.erb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
Labels: deploy

#3223 Upgrade pagy 8.6.3 => 9.0.9
  Gemfile.lock
  config/initializers/pagy.rb
  spec/features/admin/admin_payroll_runs_spec.rb
Labels: deploy

#3161 Add name and dob check to matching claims
  app/models/claim/matching_attribute_finder.rb
  spec/models/claim/matching_attribute_finder_spec.rb
  spec/models/claim_checking_tasks_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy

#3213 Update FE eligibility guidance URL
  config/locales/en.yml
Labels: deploy

#3231 [LUPEYALPHA-1101] remove radio buttons from Student Loan Plan task
  app/helpers/admin/claims_helper.rb
  app/views/admin/tasks/student_loan_plan.html.erb
  config/locales/en.yml
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_checks_further_education_payments_claim_spec.rb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/jobs/further_education_payments/provider_verification_chase_email_spec.rb
  spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
  spec/models/claim_spec.rb
  spec/support/admin_checks_feature_shared_examples.rb
Labels: deploy

#3206 Match across all policies
  app/models/policies/early_career_payments.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/levelling_up_premium_payments.rb
  app/models/policies/student_loans.rb
  spec/models/claim/matching_attribute_finder_spec.rb
Labels: deploy

#3237 [LUPEYALPHA-1045] EY practitioner find reference screen
  app/controllers/claims_controller.rb
  app/controllers/concerns/form_submittable.rb
  app/forms/current_school_form.rb
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
  app/mailers/claim_mailer.rb
  app/models/journeys/early_years_payment/practitioner/session_answers.rb
  app/views/early_years_payment/practitioner/claims/find_reference.html.erb
  config/locales/en.yml
  spec/factories/journeys/early_years_payment/practitioner/session.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
  spec/mailers/claim_mailer_spec.rb
  spec/requests/reminders_spec.rb
Labels: deploy, business reviewed
