Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-10, with the labels that each got.

#3241 [LUPEYALPHA-981] [LUPEYALPHA-994] Add One Login to EY practitioner journey
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/models/journeys/early_years_payment/practitioner/session_answers.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/early_years_payment/practitioner/claims/find_reference.html.erb
  app/views/early_years_payment/practitioner/claims/one_login_sign_in.html.erb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
Labels: deploy, business reviewed

#3252 Fix claims being flagged for qa
  app/models/claim.rb
Labels: deploy

#3256 [LUPEYALPHA-1121] Update find ref copy
  config/locales/en.yml
  spec/features/early_career_payments/early_career_payments_claim_spec.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/support/feature_helpers.rb
Labels: deploy, business reviewed

#3255 [CAPT-1472] Remove building society roll number
  app/controllers/claims_form_callbacks.rb
  app/forms/bank_details_form.rb
  app/forms/bank_or_building_society_form.rb
  app/helpers/admin/claims_helper.rb
  app/models/claim.rb
  app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
  app/models/journeys/base.rb
  app/models/journeys/base_answers_presenter.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
  app/models/journeys/session_answers.rb
  app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
  app/models/payroll/payment_csv_row.rb
  app/models/payroll/payments_csv.rb
  app/views/admin/amendments/new.html.erb
  app/views/admin/tasks/payroll_details.html.erb
  app/views/claims/_account_details.html.erb
  app/views/claims/bank_or_building_society.html.erb
  app/views/claims/building_society_account.html.erb
  app/views/claims/personal_bank_account.html.erb
  config/locales/en.yml
  spec/features/admin/admin_amend_claim_spec.rb
  spec/features/changing_answers_spec.rb
  spec/features/claim_with_mobile_sms_otp_spec.rb
  spec/features/combined_teacher_claim_journey_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
  spec/features/early_career_payments/early_career_payments_claim_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
  spec/features/hmrc_bank_validation_spec.rb
  spec/features/levelling_up_premium_payments_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_trn_spec.rb
  spec/forms/bank_details_form_spec.rb
  spec/forms/bank_or_building_society_form_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
  spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
  spec/models/payroll/payment_csv_row_spec.rb
  spec/support/get_a_teacher_relocation_payment/step_helpers.rb
  spec/support/journey_answers_presenter_shared_examples.rb
Labels: deploy, business reviewed

#3257 [CAPT-1837] Tweak TSLR copy
  app/models/policies/student_loans.rb
  app/views/student_loans/claims/student_loan_amount.html.erb
Labels: deploy, business reviewed

#3261 [CAPT-1829] Update landing page tweaks
  app/views/additional_payments/landing_page.html.erb
Labels: deploy, business reviewed

#3264 Adds new admin rejection reasons
  app/models/policies/further_education_payments.rb
  config/locales/en.yml
Labels: deploy

#3268 [CAPT-1615] Admin can view amendments after payrolled
  app/controllers/admin/amendments_controller.rb
  spec/features/admin/admin_amend_claim_spec.rb
Labels: deploy, business reviewed

#3262 [CAPT-1832] enable reminders for LUP
  app/models/concerns/eligibility_checkable.rb
  app/models/journeys/additional_payments_for_teaching.rb
  app/views/additional_payments/submissions/show.html.erb
  spec/models/journeys/additional_payments_for_teaching_spec.rb
Labels: deploy, business reviewed

#3207 [LUPEYALPHA-1004] New status for FE claims: Awaiting provider verification
  app/forms/admin/claims_filter_form.rb
  app/helpers/admin/claims_helper.rb
  app/models/claim.rb
  app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
  app/models/policies/further_education_payments/eligibility.rb
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/features/admin/admin_view_claim_further_education_payments_spec.rb
  spec/jobs/further_education_payments/provider_verification_chase_email_spec.rb
  spec/models/claim_spec.rb
Labels: deploy

#3263 [CAPT-1836] Copy update: info provided screen
  app/views/claims/information_provided.html.erb
Labels: deploy, business reviewed

#3269 CAPT 1834/claim allocations dropdown
  app/views/admin/claims/_allocations_form.html.erb
  spec/features/admin/admin_claim_allocation_spec.rb
Labels: deploy, business reviewed

#3260 Add new provider verification questions
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
  config/locales/en.yml
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Labels: deploy

#3278 [CAPT-1297] Admin claims filter and session
  app/controllers/admin/claims_controller.rb
  app/forms/admin/claims_filter_form.rb
  app/helpers/admin/claims_helper.rb
  app/views/admin/claims/index.html.erb
  spec/features/admin/admin_claims_filtering_spec.rb
  spec/features/admin/admin_view_claim_further_education_payments_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/requests/admin/admin_claims_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy, business reviewed

#3275 [CAPT-1839] content update for FE submitted page
  app/views/further_education_payments/submissions/show.html.erb
Labels: deploy

#3286 Update copy
  config/locales/en.yml
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
Labels: deploy

#3287 Update reminder copy
  app/views/additional_payments/reminders/set.html.erb
  app/views/reminders/confirmation.html.erb
Labels: deploy

#3280 [CAPT-1841] Update FE landing page copy
  app/views/further_education_payments/landing_page.html.erb
Labels: deploy, business reviewed

#3251 [LUPEYALPHA-1112] When no entry in SLC data, do not create task (shows as incomplete on admin view)
  app/models/automated_checks/claim_verifiers/student_loan_plan.rb
  app/models/policies/further_education_payments.rb
  app/views/admin/tasks/student_loan_plan.html.erb
  spec/features/admin/upload_slc_data_spec.rb
  spec/features/further_education_payments/student_loan_spec.rb
  spec/jobs/student_loan_plan_check_job_spec.rb
  spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
  spec/support/steps/dqt.rb
  spec/support/steps/further_education_journey.rb
Labels: deploy

#3297 [CAPT-1854] Provider verification status
  app/forms/admin/claims_filter_form.rb
  app/helpers/admin/claims_helper.rb
  spec/factories/claims.rb
  spec/forms/admin/claims_filter_form_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
Labels: bug, deploy

#3289 [LUPEYALPHA-1147] FE employment answer
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  config/locales/en.yml
  spec/models/policies/further_education_payments/admin_tasks_presenter_spec.rb
Labels: deploy, business reviewed

#3292 [CAPT-1402] Back office can filter for auto approved claims
  app/forms/admin/claims_filter_form.rb
  spec/factories/claims.rb
  spec/forms/admin/claims_filter_form_spec.rb
Labels: deploy, business reviewed

#3288 [CAPT-1614] Admin task pagination
  app/controllers/admin/decisions_controller.rb
  app/models/admin/task_pagination.rb
  app/models/claim_checking_tasks.rb
  app/views/admin/_task_pagination.html.erb
  app/views/admin/claims/policies/early_career_payments/_claim.html.erb
  app/views/admin/claims/policies/early_years_payments/_claim.html.erb
  app/views/admin/claims/policies/further_education_payments/_claim.html.erb
  app/views/admin/claims/policies/international_relocation_payments/_claim.html.erb
  app/views/admin/claims/policies/levelling_up_premium_payments/_claim.html.erb
  app/views/admin/claims/policies/student_loans/_claim.html.erb
  app/views/admin/decisions/index.html.erb
  app/views/admin/tasks/index.html.erb
  config/routes.rb
  spec/features/admin/tasks/pagination_spec.rb
  spec/support/admin_checks_feature_shared_examples.rb
Labels: deploy, business reviewed

#3272 [CAPT-1843] FE qualifications URLs update
  app/models/journeys/further_education_payments/courses_helper.rb
  config/locales/en.yml
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
  spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Labels: deploy

#3318 Create backup storage account for test env
  terraform/application/config/test.tfvars.json
Labels: devops

#3312 [LUPEYALPHA-1162] separate practitioner_claim_submitted_at for EY practitioner journey
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/models/policies/early_years_payments/eligibility.rb
  config/analytics.yml
  db/migrate/20241015093740_add_practitioner_claim_submitted_at_to_early_years_payment_eligibilities.rb
  db/schema.rb
  spec/factories/early_years_payments/eligibilities.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
  spec/support/steps/eligible_ey_journey_authenticated.rb
Labels: deploy

#3313 Update copy
  config/locales/en.yml
  spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
  spec/features/further_education_payments/happy_js_path_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/ineligible_paths_spec.rb
  spec/models/journeys/additional_payments_for_teaching/answers_presenter_spec.rb
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
  spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Labels: deploy

#3276 Rescue notify api errors
  app/forms/mobile_number_form.rb
  spec/forms/mobile_number_form_spec.rb
Labels: deploy

#3308 [LUPEYALPHA-1152] Upload CSV with empty rows
  app/models/eligible_fe_providers_importer.rb
  lib/csv_importer/base.rb
  spec/factories/file_uploads.rb
  spec/jobs/import_census_job_spec.rb
  spec/models/claim_spec.rb
  spec/models/eligible_fe_providers_importer_spec.rb
Labels: bug, deploy, business reviewed

#3302 [CAPT-1401] Quality assured filters
  app/forms/admin/claims_filter_form.rb
  app/views/admin/claims/index.html.erb
  spec/factories/claims.rb
  spec/forms/admin/claims_filter_form_spec.rb
Labels: deploy, business reviewed

#3322 [LUPEYALPHA-1168] Upgrade static error pages to govuk 5.7.1
  public/404.html
  public/422.html
  public/500.html
  public/favicon.ico
  public/fonts/bold-affa96571d-v2.woff
  public/fonts/bold-b542beb274-v2.woff2
  public/fonts/light-94a07e06a1-v2.woff2
  public/fonts/light-f591b13f7d-v2.woff
  public/govuk-frontend-5.3.1.min.css
  public/govuk-frontend-5.7.1.min.css
  public/images/favicon.ico
  public/images/favicon.svg
  public/images/govuk-crest.svg
  public/images/govuk-icon-180.png
  public/images/govuk-icon-192.png
  public/images/govuk-icon-512.png
  public/images/govuk-icon-mask.svg
  public/images/govuk-opengraph-image.png
  spec/features/static_error_pages_spec.rb
Labels: deploy

#3293 [LUPEYALPHA-1075] Early Years Practitioner mobile number
  app/forms/email_address_form.rb
  app/forms/mobile_number_form.rb
  app/forms/provide_mobile_number_form.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/claims/_email_address.html.erb
  app/views/claims/_mobile_number.html.erb
  app/views/claims/_one_time_password.html.erb
  app/views/claims/_provide_mobile_number.html.erb
  app/views/claims/email_address.html.erb
  app/views/claims/mobile_number.html.erb
  app/views/claims/provide_mobile_number.html.erb
  app/views/early_years_payment/practitioner/claims/check_your_answers.html.erb
  app/views/early_years_payment/practitioner/claims/email_address.html.erb
  app/views/early_years_payment/practitioner/claims/mobile_number.html.erb
  app/views/early_years_payment/practitioner/claims/mobile_verification.html.erb
  app/views/early_years_payment/practitioner/claims/provide_mobile_number.html.erb
  config/locales/en.yml
  spec/features/changing_answers_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
  spec/features/early_years_payment/practitioner/email_address_spec.rb
  spec/features/early_years_payment/practitioner/mobile_number_spec.rb
  spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
  spec/features/early_years_payment/provider/authenticated/submitter_name_omitted_spec.rb
  spec/features/early_years_payment/provider/start/happy_path_spec.rb
  spec/features/early_years_payment/provider/start/ineligible_email_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
  spec/forms/email_address_form_spec.rb
  spec/forms/mobile_number_form_spec.rb
  spec/forms/provide_mobile_number_form_spec.rb
  spec/support/steps/early_years_practitioner_journey.rb
  spec/support/steps/early_years_provider_journey_authenticated.rb
  spec/support/steps/early_years_provider_journey_start.rb
Labels: deploy, business reviewed

#3319 [LUPEYALPHA-989] EY Practitioner check-your-answers page
  app/forms/claim_submission_base_form.rb
  app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
  app/forms/journeys/early_years_payment/provider/start/claim_submission_form.rb
  app/forms/journeys/further_education_payments/claim_submission_form.rb
  app/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form.rb
  app/forms/journeys/teacher_student_loan_reimbursement/claim_submission_form.rb
  app/jobs/claim_verifier_job.rb
  app/models/journeys/early_years_payment/practitioner/answers_presenter.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/views/early_years_payment/practitioner/claims/check_your_answers.html.erb
  app/views/early_years_payment/practitioner/submissions/show.html.erb
  config/analytics.yml
  config/locales/en.yml
  db/migrate/20241017113701_add_provider_claim_submitted_at_to_early_years_payment_eligibilities.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/factories/early_years_payments/eligibilities.rb
  spec/factories/journeys/early_years_payment/practitioner/answers.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/forms/journeys/early_years_payment/practitioner/claim_submission_form_spec.rb
  spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
  spec/jobs/claim_verifier_job_spec.rb
  spec/models/journeys/early_years_payment/practitioner/answers_presenter_spec.rb
Labels: deploy, business reviewed

#3333 [CAPT-1781] Revisit OTP
  app/controllers/claims_controller.rb
  app/controllers/journeys/additional_payments_for_teaching/reminders_form_callbacks.rb
  app/forms/email_address_form.rb
  app/forms/email_verification_form.rb
  app/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form.rb
  app/forms/journeys/early_years_payment/provider/start/email_address_form.rb
  app/forms/mobile_number_form.rb
  app/forms/mobile_verification_form.rb
  app/mailers/claim_mailer.rb
  app/models/journeys/session_answers.rb
  app/models/one_time_password/base.rb
  app/models/one_time_password/generator.rb
  app/models/one_time_password/validator.rb
  config/application.rb
  lib/one_time_password.rb
  spec/forms/email_verification_form_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form_spec.rb
  spec/forms/mobile_verification_form_spec.rb
  spec/lib/one_time_password/generator_spec.rb
  spec/lib/one_time_password/validator_spec.rb
Labels: deploy

#3337 Fix link to approve/reject for reversed claims
  app/views/admin/tasks/index.html.erb
  spec/features/admin/admin_reverse_claim_decision_spec.rb
Labels: deploy

#3335 [LUPEYALPHA-1169] EY admin site claim summary
  app/helpers/admin/claim_summary_helper.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/views/admin/tasks/_claim_summary_early_years_payments.html.erb
  config/locales/en.yml
  spec/factories/early_years_payments/eligibilities.rb
  spec/features/admin/admin_view_claim_early_years_payments_spec.rb
  spec/features/admin/admin_view_claim_spec.rb
  spec/helpers/admin/claim_summary_helper_spec.rb
Labels: deploy

#3323 [LUPEYALPHA-990] EY practitioner confirmation page
  app/views/early_years_payment/practitioner/submissions/show.html.erb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
Labels: deploy

#3327 [LUPEYALPHA-1201] Use visible legends for FE questions
  app/views/further_education_payments/claims/half_teaching_hours.html.erb
  app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
Labels: deploy, business reviewed

#3326 [LUPEYALPHA-1199] Align FE page titles with h1s
  app/views/claims/_account_details.html.erb
  app/views/claims/existing_session.html.erb
  app/views/claims/personal_bank_account.html.erb
  app/views/further_education_payments/claims/further_education_provision_search.html.erb
  app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
  app/views/further_education_payments/claims/teacher_reference_number.html.erb
  app/views/further_education_payments/claims/teaching_responsibilities.html.erb
  app/views/further_education_payments/landing_page.html.erb
  config/locales/en.yml
Labels: deploy, business reviewed

#3346 Set verified at on the claim
  app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
  app/models/claim.rb
  config/analytics.yml
  db/migrate/20241028095040_add_verified_at_timestamp_to_claims.rb
  db/schema.rb
  spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Labels: deploy

#3338 [LUPEYALPHA-1170] EY full claim view
  app/controllers/admin/claims_controller.rb
  app/controllers/admin/page_controller.rb
  app/controllers/claims_controller.rb
  app/forms/claim_submission_base_form.rb
  app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/current_nursery_form.rb
  app/helpers/admin/claims_helper.rb
  app/models/claim.rb
  app/models/claim/matching_attribute_finder.rb
  app/models/claim/search.rb
  app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/admin_claim_details_presenter.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/models/school_workforce_census.rb
  app/views/admin/claims/index.html.erb
  app/views/admin/claims/policies/early_years_payments/_claim.html.erb
  app/views/admin/tasks/_claim_summary_early_years_payments.html.erb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/brakeman.ignore
  config/locales/en.yml
  db/migrate/20241021162043_add_columns_to_early_years_payment_eligibilities.rb
  db/schema.rb
  spec/factories/journeys/early_years_payment/provider/authenticated/early_years_payment_provider_authenticated_answers.rb
  spec/factories/policies/early_career_payments/eligibilities.rb
  spec/factories/policies/early_years_payments/eligibilities.rb
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_search_spec.rb
  spec/features/admin/admin_stats_spec.rb
  spec/features/admin/admin_view_claim_early_years_payments_spec.rb
  spec/features/admin/admin_view_claim_further_education_payments_spec.rb
  spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
  spec/features/early_years_payment/provider/authenticated/employee_email_spec.rb
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
  spec/features/early_years_payment/provider/authenticated/ineligible_nursery_spec.rb
  spec/features/student_loans_claim_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
  spec/mailers/previews/claim_mailer_preview.rb
  spec/models/claim/matching_attribute_finder_spec.rb
  spec/models/claim/school_check_email_data_export_spec.rb
  spec/models/claim_spec.rb
  spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy

#3342 [LUPEYALPHA-1221] Implement FE + IRP payroll csv names
  app/models/policies/further_education_payments.rb
  app/models/policies/international_relocation_payments.rb
  spec/models/policies/further_education_payments_spec.rb
  spec/models/policies/international_relocation_payments_spec.rb
Labels: deploy, business reviewed

#3349 [LUPEYALPHA-1230] make claim practitioner_email_address case insensitive
  db/migrate/20241028161228_make_claim_practitioner_email_address_citext.rb
  db/schema.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
Labels: deploy, business reviewed

#3355 [LUPEYALPHA-1234] update FE early years courses checkbox
  app/models/journeys/further_education_payments/courses_helper.rb
  config/locales/en.yml
  spec/models/journeys/further_education_payments/answers_presenter_spec.rb
Labels: deploy, business reviewed

#3350 [LUPEYALPHA-1173][LUPEYALPHA-1176] EY rejection reasons
  app/jobs/claim_verifier_job.rb
  app/mailers/application_mailer.rb
  app/models/policies.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/claim_personal_data_scrubber.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/models/policies/early_years_payments/eligibility_admin_answers_presenter.rb
  config/locales/en.yml
  spec/factories/journey_configurations.rb
  spec/factories/policies/early_years_payments/eligibilities.rb
  spec/features/admin/admin_claim_allocation_spec.rb
  spec/features/admin/admin_view_claim_spec.rb
  spec/helpers/admin/claim_summary_helper_spec.rb
  spec/jobs/claim_verifier_job_spec.rb
  spec/models/decision_spec.rb
  spec/models/policies/early_years_payments_spec.rb
  spec/models/policies_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy, business reviewed
