Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2024-11, with the labels that each got.

#3360 [LUPEYALPHA-1235] Rejecting EY claim also emails provider
  app/controllers/admin/decisions_controller.rb
  app/mailers/claim_mailer.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/eligibility.rb
  spec/features/admin/admin_reject_claim_spec.rb
  spec/mailers/claim_mailer_spec.rb
Labels: deploy, business reviewed

#3331 Add fraud check
  app/controllers/admin/fraud_risk_csv_downloads_controller.rb
  app/controllers/admin/fraud_risk_csv_uploads_controller.rb
  app/controllers/admin/tasks_controller.rb
  app/forms/admin/fraud_risk_csv_upload_form.rb
  app/models/automated_checks/claim_verifiers/fraud_risk.rb
  app/models/claim.rb
  app/models/policies.rb
  app/models/policies/early_career_payments.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/international_relocation_payments.rb
  app/models/policies/levelling_up_premium_payments.rb
  app/models/policies/student_loans.rb
  app/models/risk_indicator.rb
  app/views/admin/claims/index.html.erb
  app/views/admin/decisions/_decision_form.html.erb
  app/views/admin/fraud_risk_csv_uploads/new.html.erb
  app/views/admin/tasks/_banner.html.erb
  app/views/admin/tasks/index.html.erb
  config/analytics_blocklist.yml
  config/routes.rb
  db/migrate/20241017160838_create_risk_indicators.rb
  db/schema.rb
  spec/factories/risk_indicators.rb
  spec/features/admin/admin_fraud_prevention_spec.rb
  spec/fixtures/files/fraud_risk.csv
  spec/fixtures/files/fraud_risk_missing_headers.csv
  spec/fixtures/files/fraud_risk_missing_value.csv
  spec/fixtures/files/fraud_risk_unknown_attribute.csv
  spec/forms/admin/fraud_risk_csv_upload_form_spec.rb
  spec/models/automated_checks/claim_verifier_spec.rb
  spec/models/automated_checks/claim_verifiers/fraud_risk_spec.rb
  spec/models/claim_spec.rb
  spec/models/early_career_payments_spec.rb
  spec/models/further_education_payments_spec.rb
  spec/models/levelling_up_premium_payments_spec.rb
  spec/models/student_loans_spec.rb
Labels: deploy, business reviewed

#3339 Don't show DQT match if DQT record not found
  app/views/admin/tasks/_form.html.erb
  config/locales/en.yml
  spec/features/admin/admin_claim_without_verified_identity_spec.rb
Labels: deploy, business reviewed

#3336 Remove batching from payroll csv
  app/controllers/admin/payroll_run_downloads_controller.rb
  app/controllers/admin/payroll_runs_controller.rb
  app/models/payroll/payment_csv_row.rb
  app/models/payroll/payments_csv.rb
  app/models/payroll_run.rb
  app/views/admin/payroll_run_downloads/show.html.erb
  spec/features/admin/admin_payroll_run_download_spec.rb
  spec/features/admin/admin_payroll_runs_spec.rb
  spec/models/payroll/payment_csv_row_spec.rb
  spec/models/payroll/payments_csv_spec.rb
  spec/models/payroll_run_spec.rb
  spec/requests/admin/admin_payroll_run_downloads_spec.rb
  spec/requests/admin/admin_payroll_runs_spec.rb
Labels: deploy, business reviewed

#3362 [LUPEYALPHA-1231] EY student loan plan task
  app/controllers/claims_form_callbacks.rb
  app/jobs/student_loan_plan_check_job.rb
  app/models/claim_checking_tasks.rb
  app/models/journeys/early_years_payment/practitioner/answers_student_loans_details_updater.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/claim_checking_tasks.rb
  spec/features/admin/upload_slc_data_spec.rb
  spec/features/early_years_payment/practitioner/email_address_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/features/early_years_payment/practitioner/mobile_number_spec.rb
  spec/features/early_years_payment/practitioner/student_loan_spec.rb
  spec/jobs/student_loan_plan_check_job_spec.rb
  spec/requests/admin/admin_student_loans_data_upload_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
  spec/support/steps/early_years_practitioner_journey.rb
  spec/support/steps/early_years_provider_journey_authenticated.rb
  spec/support/steps/eligible_ey_providers.rb
Labels: deploy

#3359 LUPEYALPHA 1171/identity task
  app/controllers/admin/tasks_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/jobs/claim_verifier_job.rb
  app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/admin_tasks_presenter.rb
  app/models/policies/early_years_payments/claim_checking_tasks.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/views/admin/tasks/early_years_payments/identity_confirmation.html.erb
  config/brakeman.ignore
  config/locales/en.yml
  spec/features/admin/admin_ey_identity_task_spec.rb
  spec/jobs/claim_verifier_job_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy

#3364 [LUPEYALPHA-1175] Can filter for EY awaiting states
  app/forms/admin/claims_filter_form.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/eligibility.rb
  spec/forms/admin/claims_filter_form_spec.rb
Labels: deploy, business reviewed

#3365 [LUPEYALPHA-1241] Extra EY rejection reason: ID check failed
  app/models/policies/early_years_payments.rb
  config/locales/en.yml
  spec/models/decision_spec.rb
Labels: deploy, business reviewed

#3372 [CAPT-1938] Tweak EY journey name
  config/locales/en.yml
  spec/features/admin/eligible_ey_providers_spec.rb
Labels: deploy, business reviewed

#3368 [CAPT-1937] EY approvable only after passed employment task
  app/models/base_policy.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/claim_checking_tasks.rb
  spec/factories/claims.rb
  spec/models/claim_spec.rb
  spec/models/policies/early_years_payments/claim_checking_tasks_spec.rb
  spec/models/policies/early_years_payments_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
Labels: deploy, business reviewed

#3366 [CAPT-1921] EY claim index data
  app/helpers/admin/claims_helper.rb
  app/models/base_policy.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  app/views/admin/claims/index.html.erb
  spec/factories/claims.rb
  spec/features/admin/admin_view_claim_early_years_payments_spec.rb
  spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/models/base_policy_spec.rb
  spec/models/claim_spec.rb
  spec/models/policies/early_years_payments_spec.rb
  spec/support/page_matchers.rb
Labels: deploy, business reviewed

#3343 [CAPT-1957] Handle currency for eligble FE CSV upload
  app/models/eligible_fe_providers_importer.rb
  lib/csv_importer/base.rb
  spec/fixtures/files/eligible_fe_providers_illegal_encoding.csv
  spec/models/eligible_fe_providers_importer_spec.rb
Labels: deploy, business reviewed

#3236 Add task if provider / claimant details match
  app/models/claim_checking_tasks.rb
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  app/models/policies/further_education_payments/claim_checking_tasks.rb
  app/models/policies/further_education_payments/eligibility.rb
  app/models/task.rb
  app/views/admin/tasks/provider_details.html.erb
  config/locales/en.yml
  spec/features/admin/admin_checks_further_education_payments_claim_spec.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
  spec/models/policies/further_education_payments/claim_checking_tasks_spec.rb
Labels: deploy, business reviewed

#3377 [CAPT-1933] EY start date eligibility
  app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/early_years_payments/policy_eligibility_checker.rb
  app/views/early_years_payment/provider/authenticated/claims/_ineligibility_start_date_before_policy_start.html.erb
  app/views/early_years_payment/provider/start/landing_page.html.erb
  spec/factories/journeys/early_years_payment/provider/authenticated/early_years_payment_provider_authenticated_answers.rb
  spec/features/admin/admin_ey_identity_task_spec.rb
  spec/features/early_years_payment/provider/authenticated/ineligible_start_date_spec.rb
  spec/models/journeys/early_years_payment/provider/authenticated/answers_presenter_spec.rb
  spec/models/policies/early_years_payments/policy_eligibility_checker_spec.rb
Labels: deploy, business reviewed

#3381 [CAPT-1898] Practitioner claim start timestamp
  app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
  app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
  app/models/journeys/early_years_payment/practitioner/session_answers.rb
  scratch
  spec/factories/journeys/early_years_payment/practitioner/answers.rb
  spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
Labels: deploy, business reviewed

#3383 [CAPT-1904] Update email address for EY links
  config/locales/en.yml
Labels: deploy, business reviewed

#3385 [CAPT-1911][CAPT-1968] EY submission emails
  app/forms/claim_submission_base_form.rb
  app/mailers/application_mailer.rb
  app/mailers/claim_mailer.rb
  app/mailers/early_years_payments_mailer.rb
  app/models/base_policy.rb
  app/models/policies/early_years_payments.rb
  spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
Labels: deploy, business reviewed

#3242 Upgrade to govuk 5.4 => 5.6
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: deploy

#3399 [CAPT-1971] Copy tweak for ineligible nursery
  app/views/early_years_payment/provider/authenticated/claims/_ineligibility_nursery_is_not_listed.html.erb
  app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
Labels: deploy, business reviewed

#3400 [CAPT-1976] Copy tweak EY practitioner confirmation
  app/views/early_years_payment/practitioner/submissions/show.html.erb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
Labels: deploy, business reviewed

#3398 unique indexes for FE + EY providers
  db/migrate/20241113111916_fe_providers_unique.rb
  db/migrate/20241113112028_ey_providers_unique.rb
  db/schema.rb
Labels: deploy

#3396 [CAPT-1908] EY progress update emails
  app/jobs/early_years_progress_emails_job.rb
  app/jobs/send_emails_after_three_weeks_job.rb
  app/mailers/early_years_payments_mailer.rb
  app/models/base_policy.rb
  app/models/claim.rb
  app/models/policies/early_years_payments.rb
  config/initializers/core_ext.rb
  lib/core_ext/date.rb
  spec/jobs/early_years_progress_emails_job_spec.rb
  spec/mailers/early_years_payments_mailer_spec.rb
  spec/models/claim_spec.rb
Labels: deploy

#3409 [CAPT-1984] EY clear dependent answers
  app/controllers/concerns/form_submittable.rb
  app/forms/current_school_form.rb
  app/forms/form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/current_nursery_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/returner_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form.rb
  app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
  app/forms/journeys/get_a_teacher_relocation_payment/entry_date_form.rb
  app/forms/journeys/get_a_teacher_relocation_payment/start_date_form.rb
  app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
  app/forms/personal_details_form.rb
  app/models/journeys/base.rb
  app/models/journeys/early_years_payment/provider/authenticated/answers_presenter.rb
  spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/returner_form_spec.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form_spec.rb
  spec/support/steps/early_years_provider_journey_authenticated.rb
Labels: deploy, business reviewed

#3412 [CAPT-1965] Update EY policy start date => 15/11/2024
  Dockerfile
  app/models/policies/early_years_payments.rb
  spec/features/admin/admin_ey_tasks_spec.rb
Labels: deploy, business reviewed

#3410 Send emails when claim approved
  app/controllers/admin/decisions_controller.rb
  app/mailers/early_years_payments_mailer.rb
  app/models/claim_auto_approval.rb
  spec/factories/claims.rb
  spec/features/admin/approvals_spec.rb
Labels: deploy

#3411 [CAPT-1915] Improve admin allocations
  app/controllers/admin/allocations_controller.rb
  app/views/admin/allocations/bulk_deallocate.html.erb
  spec/features/admin/admin_claim_allocation_spec.rb
Labels: deploy, business reviewed

#3417 [CAPT-2010] EY consent form
  app/assets/pdfs/ey-provider-practitioner-consent-form.pdf
  app/assets/stylesheets/components/document.scss
  app/views/early_years_payment/provider/start/landing_page.html.erb
  app/views/shared/_document.html.erb
  app/views/shared/_generic_document_icon.html.erb
  app/views/shared/_pdf_document_icon.html.erb
  config/initializers/assets.rb
Labels: deploy, business reviewed

#3422 Implement EY provider guidance page
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/box.scss
  app/controllers/journeys/early_years_payment/provider/start/static_pages_controller.rb
  app/views/early_years_payment/provider/start/guidance.html.erb
  app/views/early_years_payment/provider/start/landing_page.html.erb
  config/routes.rb
  spec/features/early_years_payment/provider/start/happy_path_spec.rb
  terraform/application/config/production_app_env.yml
  terraform/application/config/review_app_env.yml
  terraform/application/config/test_app_env.yml
Labels: deploy

#3421 [CAPT-1323] Upgrade rails 7.0.8.5 => 7.1.5
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/amendment.rb
  app/views/admin/tasks/_form.html.erb
  config/environments/test.rb
  config/locales/en.yml
  config/routes.rb
  lib/tasks/default.rake
  spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
  spec/features/early_career_payments/early_career_payments_claim_spec.rb
  spec/forms/form_spec.rb
  spec/helpers/admin/journey_configurations_helper_spec.rb
  spec/helpers/admin/payroll_run_helper_spec.rb
  spec/jobs/early_years_progress_emails_job_spec.rb
  spec/models/academic_year_spec.rb
  spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
  spec/models/policies/early_years_payments/eligibility_spec.rb
  spec/models/policies/international_relocation_payments/claim_personal_data_scrubber_spec.rb
  spec/support/admin_view_claim_feature_shared_examples.rb
  spec/support/admin_view_claim_logged_in_with_tid_feature_shared_examples.rb
Labels: deploy

#3425 [CAPT-2017] Copy tweak: add OL mandatory for FE
  app/views/claims/_sign_in_1_start.html.erb
  app/views/further_education_payments/landing_page.html.erb
Labels: deploy

#3428 [CAPT-2027] Fix EY practitioner answer
  app/models/journeys/early_years_payment/practitioner/answers_presenter.rb
  spec/models/journeys/early_years_payment/practitioner/answers_presenter_spec.rb
Labels: deploy, business reviewed

#3413 Use new reminders controller + remove old version
  app/controllers/journeys/additional_payments_for_teaching/reminders_controller.rb
  app/controllers/journeys/additional_payments_for_teaching/reminders_form_callbacks.rb
  app/controllers/reminders_controller.rb
  app/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form.rb
  app/forms/journeys/additional_payments_for_teaching/reminders/personal_details_form.rb
  app/forms/reminders/confirmation_form.rb
  app/forms/reminders/email_verification_form.rb
  app/forms/reminders/personal_details_form.rb
  app/models/journeys/additional_payments_for_teaching.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/session_answers.rb
  app/models/policies/further_education_payments/eligibility.rb
  app/views/additional_payments/claims/eligible_later.html.erb
  app/views/additional_payments/claims/future_eligibility.html.erb
  app/views/additional_payments/reminders/_one_time_password.html.erb
  app/views/additional_payments/reminders/email_verification.html.erb
  app/views/additional_payments/reminders/personal_details.html.erb
  app/views/additional_payments/reminders/set.html.erb
  app/views/additional_payments/submissions/_reminder.html.erb
  app/views/further_education_payments/submissions/show.html.erb
  app/views/reminders/email_verification.html.erb
  app/views/reminders/personal_details.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/reminders_spec.rb
  spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/reminders/personal_details_form_spec.rb
  spec/requests/reminders_spec.rb
Labels: deploy

#3433 [CAPT-2013] OTP email now personalises with journey name
  app/forms/email_address_form.rb
  app/forms/reminders/personal_details_form.rb
  app/mailers/claim_mailer.rb
  app/mailers/reminder_mailer.rb
  app/models/journeys/base.rb
  app/models/journeys/session.rb
  spec/forms/email_address_form_spec.rb
  spec/mailers/claim_mailer_spec.rb
Labels: deploy

#3440 Upgrade govuk frontend 5.6.0 => 5.7.1
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: deploy

#3419 Add maintenance page
  .github/workflows/maintenance.yml
  Makefile
  maintenance_page/Dockerfile
  maintenance_page/html/assets/fonts/bold-affa96571d-v2-b092ddd6.woff
  maintenance_page/html/assets/fonts/bold-b542beb274-v2-616e5f21.woff2
  maintenance_page/html/assets/fonts/light-94a07e06a1-v2-bb962e0c.woff2
  maintenance_page/html/assets/fonts/light-f591b13f7d-v2-f03d82c2.woff
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.br
  maintenance_page/html/assets/images/favicon-7ddbfd51.ico.gz
  maintenance_page/html/assets/images/favicon-ec189703.svg
  maintenance_page/html/assets/images/favicon-ec189703.svg.br
  maintenance_page/html/assets/images/favicon-ec189703.svg.gz
  maintenance_page/html/assets/images/govuk-crest-2x.png
  maintenance_page/html/assets/images/govuk-crest.png
  maintenance_page/html/assets/images/govuk-icon-180-e0835e78.png
  maintenance_page/html/assets/images/govuk-icon-192-7b8e00f8.png
  maintenance_page/html/assets/images/govuk-icon-512-587f7e53.png
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.br
  maintenance_page/html/assets/images/govuk-icon-mask-c3a9868b.svg.gz
  maintenance_page/html/assets/images/govuk-opengraph-image-bd4c811b.png
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg
  maintenance_page/html/assets/images/icon-close-cross-black-692c7df5.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-5a9b07c6.svg.gz
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.br
  maintenance_page/html/assets/images/icon-tag-remove-cross-white-d540bf9f.svg.gz
  maintenance_page/html/assets/images/icon-toggle-plus-minus-257426a1.svg
  maintenance_page/html/index.html
  maintenance_page/html/javascript/govuk-frontend-5.3.1.min.js
  maintenance_page/html/stylesheets/govuk-frontend-5.3.1.min.css
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
  maintenance_page/manifests/maintenance/service_maintenance.yml
  maintenance_page/manifests/production/ingress_internal_to_main.yml
  maintenance_page/manifests/production/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/production/ingress_maintenance.yml
  maintenance_page/manifests/production/ingress_temp_to_main.yml
  maintenance_page/manifests/test/ingress_internal_to_main.yml
  maintenance_page/manifests/test/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/test/ingress_maintenance.yml
  maintenance_page/manifests/test/ingress_temp_to_main.yml
  maintenance_page/nginx.conf
  maintenance_page/scripts/failback.sh
  maintenance_page/scripts/failover.sh
Labels: devops

#3418 Add manual env deployment option
  .github/workflows/build_and_deploy.yml
Labels: devops, deploy

#3437 [CAPT-2030] Fix EY started_at timestamp
  app/forms/claim_submission_base_form.rb
  app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
  spec/forms/journeys/early_years_payment/practitioner/claim_submission_form_spec.rb
Labels: deploy, business reviewed

#3436 Reminders store journey
  app/controllers/admin/journey_configurations_controller.rb
  app/forms/email_address_form.rb
  app/forms/reminders/confirmation_form.rb
  app/forms/reminders/email_verification_form.rb
  app/forms/reminders/personal_details_form.rb
  app/jobs/send_reminder_email_job.rb
  app/jobs/send_reminder_emails_job.rb
  app/mailers/reminder_mailer.rb
  app/models/journeys/base.rb
  app/models/reminder.rb
  app/views/admin/journey_configurations/_ecp_reminder_warning.html.erb
  config/analytics.yml
  db/migrate/20241126105650_add_journey_class_to_reminders.rb
  db/schema.rb
  spec/factories/reminders.rb
  spec/features/admin/admin_configure_services_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/reminders_spec.rb
  spec/forms/email_address_form_spec.rb
  spec/jobs/send_reminder_emails_job_spec.rb
  spec/lib/tasks/fix_student_loan_repayment_amounts_spec.rb
  spec/models/reminder_spec.rb
Labels: deploy
