Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2025-03, with the labels that each got.

#3623 [CAPT-2080] Fix amend claim DOB validation
  app/controllers/admin/amendments_controller.rb
  app/forms/admin/amendment_form.rb
  app/helpers/admin/amendments_helper.rb
  app/views/admin/amendments/new.html.erb
  spec/forms/admin/amendment_form_spec.rb
  spec/helpers/admin/amendments_helper_spec.rb
  spec/requests/admin/admin_amendments_spec.rb
Labels: deploy

#3620 1972 implement ci cd for domains on all services
  .github/workflows/build_and_deploy.yml
  terraform/domains/environment_domains/output.tf
Labels: devops

#3628 Fix admin amend claim
  app/forms/admin/amendment_form.rb
  app/models/policies/further_education_payments/eligibility.rb
  spec/forms/admin/amendment_form_spec.rb
Labels: deploy

#3562 CAPT-2189/closed service access
  app/controllers/concerns/part_of_claim_journey.rb
  app/controllers/journeys/early_years_payment/provider/start/static_pages_controller.rb
  app/controllers/static_pages_controller.rb
  app/controllers/submissions_controller.rb
  app/forms/claim_submission_base_form.rb
  app/forms/journeys/session_form.rb
  app/models/journeys/base.rb
  app/models/journeys/service_access_code.rb
  app/models/journeys/session.rb
  app/models/journeys/session_answers.rb
  app/views/additional_payments/landing_page.html.erb
  app/views/early_years_payment/provider/start/landing_page.html.erb
  app/views/further_education_payments/landing_page.html.erb
  app/views/get_a_teacher_relocation_payment/landing_page.html.erb
  app/views/student_loans/landing_page.html.erb
  config/analytics_blocklist.yml
  db/migrate/20250207140932_create_journeys_service_access_codes.rb
  db/migrate/20250226151104_add_used_to_journeys_service_access_codes.rb
  db/schema.rb
  spec/factories/journeys/service_access_code.rb
  spec/features/accessing_closed_service_spec.rb
  spec/models/journeys/service_access_code_spec.rb
Labels: deploy

#3629 [CAPT-2180] Amend banking name
  app/controllers/admin/amendments_controller.rb
  app/controllers/admin/auth_controller.rb
  app/forms/admin/amendment_form.rb
  app/models/dfe_sign_in/user.rb
  app/views/admin/amendments/new.html.erb
  app/views/admin/auth/sign_in.html.erb
  config/routes.rb
  spec/features/admin/admin_amend_claim_spec.rb
  spec/forms/admin/amendment_form_spec.rb
  spec/support/feature_helpers.rb
Labels: deploy

#3638 swap out selenium for cuprite
  Dockerfile
  Gemfile
  Gemfile.lock
  spec/features/admin/cookies_spec.rb
  spec/features/cookies_spec.rb
  spec/features/dfe_identity_sign_in_journey_spec.rb
  spec/features/further_education_payments/college_not_found_spec.rb
  spec/features/subjects_taught_spec.rb
  spec/spec_helper.rb
  spec/support/capybara.rb
  spec/support/webmock.rb
Labels: deploy

#3619 [CAPT-2249] OL without idv
  app/controllers/omniauth_callbacks_controller.rb
  app/forms/journeys/further_education_payments/claim_submission_form.rb
  app/models/automated_checks/claim_verifiers/identity.rb
  app/models/journeys/session_answers.rb
  app/views/claims/_sign_in.html.erb
  app/views/claims/_sign_in_3_not_identified.html.erb
  config/analytics.yml
  db/migrate/20250227151439_add_ol_claim_return_codes.rb
  db/schema.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/features/further_education_payments/one_login_without_idv_spec.rb
  spec/rails_helper.rb
  spec/support/feature_flags.rb
  spec/support/feature_helpers.rb
  spec/support/one_login_helper.rb
  spec/support/steps/early_years_practitioner_journey.rb
Labels: Do not merge, deploy

#3633 [CAPT-2270] FE alternative idv collects passport
  app/forms/journeys/further_education_payments/passport_form.rb
  app/models/journeys/further_education_payments.rb
  app/models/journeys/further_education_payments/answers_presenter.rb
  app/models/journeys/further_education_payments/session_answers.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/views/further_education_payments/claims/passport.html.erb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/locales/en.yml
  db/migrate/20250310152749_add_passport_to_fe_eligibilities.rb
  db/schema.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/further_education_payments/one_login_without_idv_spec.rb
  spec/forms/journeys/further_education_payments/passport_form_spec.rb
  spec/models/policies/targeted_retention_incentive_payments/award_csv_importer_spec.rb
Labels: deploy

#3654 [CAPT-2192] Remove extra indexes
  db/migrate/20250319095448_remove_extra_indexes.rb
  db/schema.rb
  spec/features/student_loans_claim_spec.rb
Labels: deploy

#3657 Revert "[CAPT-2192] Remove extra indexes"
  db/migrate/20250319095448_remove_extra_indexes.rb
  db/schema.rb
  spec/features/student_loans_claim_spec.rb
Labels: deploy

#3659 [CAPT-2259] Change EY practitioner journey order
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
  spec/features/admin/admin_ey_tasks_spec.rb
  spec/features/early_years_payment/practitioner/find_reference_spec.rb
  spec/features/early_years_payment/practitioner/happy_path_spec.rb
  spec/support/steps/early_years_practitioner_journey.rb
Labels: deploy

#3647 [CAPT-2281] One login task status
  app/helpers/admin/claims_helper.rb
  app/models/automated_checks/claim_verifiers/one_login_identity.rb
  app/models/task.rb
  app/views/admin/tasks/_task_outcome.html.erb
  app/views/admin/tasks/_task_outcome_one_login_identity.html.erb
  app/views/admin/tasks/identity_confirmation.html.erb
  app/views/admin/tasks/one_login_identity.html.erb
  config/analytics.yml
  db/migrate/20250317120537_add_reason_to_tasks.rb
  db/schema.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/models/automated_checks/claim_verifiers/one_login_identity_spec.rb
  spec/views/admin/tasks/one_login_identity.html.erb_spec.rb
Labels: deploy

#3651 [CAPT-2194] add titles to iframes
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
Labels: deploy

#3664 CAPT 2272/content fixes
  config/locales/en.yml
Labels: deploy

#3667 Send emails to both contacts
  app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
  app/mailers/early_years_payments_mailer.rb
  app/models/eligible_ey_provider.rb
  spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
Labels: deploy

#3653 CAPT 2280/alternative idv task
  app/helpers/admin/claims_helper.rb
  app/models/automated_checks/claim_verifiers/alternative_identity_verification.rb
  app/models/claim.rb
  app/models/journeys/further_education_payments/provider/session_answers.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/further_education_payments/admin_alternative_identity_verification_task_presenter.rb
  app/models/policies/further_education_payments/admin_tasks_presenter.rb
  app/models/policies/further_education_payments/claim_checking_tasks.rb
  app/models/task.rb
  app/models/tasks.rb
  app/views/admin/tasks/_alternative_identity_verification_submitted.html.erb
  app/views/admin/tasks/alternative_identity_verification.html.erb
  app/views/admin/tasks/provider_verification.html.erb
  config/locales/en.yml
  spec/factories/policies/further_education_payments/eligibilities.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
  spec/models/automated_checks/claim_verifiers/alternative_identity_verification_spec.rb
  spec/models/further_education_payments_spec.rb
  spec/models/policies/further_education_payments/claim_checking_tasks_spec.rb
  spec/models/tasks_spec.rb
Labels: deploy

#3663 [CAPT-2274] Fix OL sign out when OL bypassed
  app/controllers/deauth_controller.rb
  app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
  spec/features/early_years_payment/practitioner/signing_out_spec.rb
  spec/requests/deauth_spec.rb
Labels: deploy

#3674 link to alt idv task from OL task
  app/views/admin/tasks/_task_outcome_one_login_identity.html.erb
Labels: deploy

#3672 CAPT 2310/cant approve claim with failed idv
  app/models/policies/further_education_payments.rb
  spec/features/admin/admin_claim_further_education_payments_spec.rb
Labels: deploy
