Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2025-02, with the labels that each got.

#3491 Show the ol and claimant entered DOB
  app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
  app/models/policies/early_years_payments/admin_tasks_presenter.rb
  app/models/policies/early_years_payments/eligibility.rb
  app/views/admin/tasks/early_years_payments/identity_confirmation.html.erb
  spec/features/admin/admin_ey_tasks_spec.rb
  spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
Labels: deploy

#3494 CAPT 1941/admin date formats
  app/helpers/admin/claims_helper.rb
  app/helpers/admin/timeline_helper.rb
  app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
  app/models/policies/early_years_payments/admin_claim_details_presenter.rb
  app/models/policies/early_years_payments/admin_tasks_presenter.rb
  app/views/admin/tasks/_claim_summary.html.erb
  app/views/admin/tasks/_claim_summary_early_years_payments.html.erb
  app/views/admin/tasks/_claim_summary_further_education_payments.html.erb
  app/views/admin/tasks/_claim_summary_international_relocation_payments.html.erb
  spec/features/admin/admin_amend_claim_spec.rb
  spec/features/admin/admin_ey_tasks_spec.rb
  spec/features/admin/admin_view_claim_early_years_payments_spec.rb
  spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
  spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
  spec/helpers/admin/claims_helper_spec.rb
  spec/helpers/admin/timeline_helper_spec.rb
  spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
  spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
Labels: deploy

#3544 Fix date format
  app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
  spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
  spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
Labels: deploy

#3551 [CAPT-2124] Change test environment cookie key
  config/initializers/session_store.rb
Labels: deploy

#3537 Make email address validation notify compliant
  app/forms/email_address_form.rb
  app/forms/reminders/personal_details_form.rb
  app/forms/select_email_form.rb
  app/models/eligible_fe_provider.rb
  app/validators/email_address_format_validator.rb
  config/application.rb
  spec/validators/email_address_format_validator_spec.rb
Labels: deploy

#3554 FE address fix
  app/forms/postcode_search_form.rb
  app/forms/select_home_address_form.rb
  app/models/journeys/further_education_payments/slug_sequence.rb
  app/views/claims/select_home_address.html.erb
  config/locales/en.yml
  spec/features/further_education_payments/jump_around_spec.rb
Labels: deploy

#3555 Don't cache admin pages
  app/controllers/admin/base_admin_controller.rb
Labels: deploy

#3552 Payments show
  app/controllers/admin/payments_controller.rb
  app/models/payment.rb
  app/views/admin/payments/index.html.erb
  app/views/admin/payments/show.html.erb
  app/views/admin/payroll_runs/_complete.html.erb
  config/routes.rb
  spec/features/admin/admin_views_payment_spec.rb
  spec/models/payment_spec.rb
Labels: deploy

#3560 Add security recommendations to maint page
  maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
Labels: devops

#3575 Remove survey link and copy
  app/views/further_education_payments/submissions/show.html.erb
Labels: deploy

#3568 Navigator supports changing answers
  app/forms/form.rb
  app/forms/journeys/further_education_payments/building_construction_courses_form.rb
  app/forms/journeys/further_education_payments/chemistry_courses_form.rb
  app/forms/journeys/further_education_payments/computing_courses_form.rb
  app/forms/journeys/further_education_payments/early_years_courses_form.rb
  app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
  app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
  app/forms/journeys/further_education_payments/half_teaching_hours_form.rb
  app/forms/journeys/further_education_payments/maths_courses_form.rb
  app/forms/journeys/further_education_payments/physics_courses_form.rb
  app/forms/journeys/further_education_payments/subjects_taught_form.rb
  app/forms/journeys/further_education_payments/teaching_qualification_form.rb
  app/forms/poor_performance_form.rb
  app/models/journeys/navigator.rb
  app/views/claims/_check_your_answers_section.html.erb
  app/views/claims/_confirmation_form.html.erb
  app/views/claims/_current_school_search.html.erb
  app/views/claims/_current_school_search_results.html.erb
  app/views/claims/_email_address.html.erb
  app/views/claims/_mobile_number.html.erb
  app/views/claims/_one_time_password.html.erb
  app/views/claims/_personal_details_page.html.erb
  app/views/claims/_provide_mobile_number.html.erb
  app/views/claims/_sign_in_3_identified.html.erb
  app/views/claims/address.html.erb
  app/views/claims/correct_school.html.erb
  app/views/claims/gender.html.erb
  app/views/claims/personal_bank_account.html.erb
  app/views/claims/postcode_search.html.erb
  app/views/claims/reset_claim.erb
  app/views/claims/select_email.html.erb
  app/views/claims/select_home_address.html.erb
  app/views/claims/select_mobile.html.erb
  app/views/claims/teacher_reference_number.html.erb
  app/views/further_education_payments/claims/_courses.html.erb
  app/views/further_education_payments/claims/contract_type.html.erb
  app/views/further_education_payments/claims/fixed_term_contract.html.erb
  app/views/further_education_payments/claims/further_education_teaching_start_year.html.erb
  app/views/further_education_payments/claims/half_teaching_hours.html.erb
  app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
  app/views/further_education_payments/claims/poor_performance.html.erb
  app/views/further_education_payments/claims/postcode_search.html.erb
  app/views/further_education_payments/claims/subjects_taught.html.erb
  app/views/further_education_payments/claims/taught_at_least_one_term.html.erb
  app/views/further_education_payments/claims/teacher_reference_number.html.erb
  app/views/further_education_payments/claims/teaching_hours_per_week.html.erb
  app/views/further_education_payments/claims/teaching_hours_per_week_next_term.html.erb
  app/views/further_education_payments/claims/teaching_responsibilities.html.erb
  spec/features/changing_answers_spec.rb
  spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
  spec/features/further_education_payments/change_answers_spec.rb
  spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
  spec/features/levelling_up_premium_payments_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
  spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
  spec/forms/journeys/further_education_payments/half_teaching_hours_form_spec.rb
  spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
  spec/forms/journeys/further_education_payments/teaching_qualification_form_spec.rb
  spec/forms/poor_performance_form_spec.rb
Labels: deploy

#3585 Only create tables if they exists
  db/migrate/20250210114746_create_targeted_retention_incentive_payments_eligibilities.rb
  db/migrate/20250210115829_create_targeted_retention_incentive_payments_awards.rb
Labels: deploy

#3583 CAPT-2235/qa rejected claims
  app/models/claim.rb
  app/models/policies/early_career_payments.rb
  app/models/policies/early_years_payments.rb
  app/models/policies/further_education_payments.rb
  app/models/policies/international_relocation_payments.rb
  app/models/policies/student_loans.rb
  app/models/policies/targeted_retention_incentive_payments.rb
  app/views/admin/decisions/_decision_form.html.erb
  spec/features/admin/admin_reject_claim_spec.rb
  spec/features/admin/approvals_spec.rb
  spec/models/claim_spec.rb
  spec/support/admin_checks_feature_shared_examples.rb
  spec/support/have_received_email_matcher.rb
  spec/support/stubbing_helpers.rb
Labels: deploy

#3566 feat: Adding new credential veriables for CAPT
  .github/actions/deploy-environment/action.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/database_backup.yml
  .github/workflows/database_restore.yml
  .github/workflows/delete_review_app.yml
  .github/workflows/maintenance.yml
  .github/workflows/postgres-ptr.yml
  Makefile
  terraform/application/terraform.tf
Labels: devops, deploy

#3595 Don't allow verifying rejected claims
  app/models/journeys/further_education_payments/provider/slug_sequence.rb
  app/views/further_education_payments/provider/claims/expired_link.html.erb
  spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
Labels: deploy

#3592 [CAPT-2239] Add beta survey link to EY journeys
  app/views/early_years_payment/practitioner/submissions/show.html.erb
  app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
Labels: deploy

#3582 [CAPT-2195] OL return codes
  app/controllers/omniauth_callbacks_controller.rb
  app/models/stat.rb
  app/models/stats/one_login.rb
  config/analytics.yml
  config/initializers/omniauth.rb
  db/migrate/20250213153245_create_stats_table.rb
  db/migrate/20250214095211_add_type_to_stats.rb
  db/schema.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
Labels: Do not merge

#3597 CAPT-2240/new fe rejection reason
  app/models/policies/further_education_payments.rb
  config/locales/en.yml
Labels: deploy
