Repository DFE-Digital/claim-additional-payments-for-teaching, pull requests merged in 2025-01, with the labels that each got.

#3479 Remove accessibility statment for EY
  app/views/layouts/application.html.erb
Labels: deploy

#3476 Include claim reference in rollbar errors
  app/jobs/application_job.rb
Labels: deploy

#3481 Migrate gcp wif
  .github/actions/deploy-environment/action.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/delete_review_app.yml
  config/initializers/dfe_analytics.rb
  terraform/application/application.tf
  terraform/application/config/production.tfvars.json
  terraform/application/config/review.tfvars.json
  terraform/application/config/test.tfvars.json
  terraform/application/dfe_analytics.tf
  terraform/application/variables.tf
Labels: devops, deploy

#3490 [CAPT-649] Correct field types
  app/views/claims/_email_address.html.erb
  app/views/claims/_one_time_password.html.erb
  app/views/claims/personal_bank_account.html.erb
  app/views/claims/teacher_reference_number.html.erb
  app/views/further_education_payments/claims/teacher_reference_number.html.erb
Labels: deploy

#3486 [CAPT-650] Enable OTP autocomplete
  app/views/claims/_one_time_password.html.erb
Labels: deploy

#3480 Display the urn on the employment task
  app/models/policies/early_years_payments/admin_tasks_presenter.rb
  spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
Labels: deploy

#3454 [CAPT-2051] Better OL name
  app/controllers/omniauth_callbacks_controller.rb
  app/models/claim.rb
  app/models/journeys/session_answers.rb
  app/models/one_login/core_identity_validator.rb
  config/analytics_blocklist.yml
  db/migrate/20241205121421_add_ol_full_name_to_claims.rb
  db/schema.rb
  spec/factories/claims.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
  spec/models/automated_checks/claim_verifiers/identity_spec.rb
  spec/models/claim_spec.rb
  spec/models/one_login/core_identity_validator_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
Labels: deploy

#3498 gcp wif test deployment
  terraform/application/config/test.tfvars.json
Labels: devops

#3508 Fix ssl check statuscake monitoring
  terraform/application/config/production.tfvars.json
  terraform/application/statuscake.tf
  terraform/application/variables.tf
Labels: devops

#3510 Fix bundling in docker image
  Dockerfile
Labels: deploy

#3518 Update nginx base image
  maintenance_page/Dockerfile
Labels: devops, deploy

#3445 [CAPT-1862] Add unsubscribe functionality
  app/controllers/unsubscribe_controller.rb
  app/forms/reminders/email_verification_form.rb
  app/forms/reminders/personal_details_form.rb
  app/forms/unsubscribe/confirmation_form.rb
  app/mailers/reminder_mailer.rb
  app/models/concerns/deletable.rb
  app/models/reminder.rb
  app/views/reminders/confirmation.html.erb
  app/views/unsubscribe/create.html.erb
  app/views/unsubscribe/show.html.erb
  app/views/unsubscribe/subscription_not_found.html.erb
  config/analytics.yml
  config/environments/development.rb
  config/environments/test.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20241206105631_add_deleted_at_to_reminders.rb
  db/schema.rb
  spec/factories/reminders.rb
  spec/features/unsubscribe_spec.rb
  spec/forms/current_school_form_spec.rb
  spec/forms/employed_directly_form_spec.rb
  spec/forms/form_spec.rb
  spec/forms/gender_form_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/entire_term_contract_form_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/induction_completed_form_spec.rb
  spec/forms/journeys/additional_payments_for_teaching/itt_academic_year_form_spec.rb
  spec/forms/journeys/teacher_student_loan_reimbursement/claim_school_form_spec.rb
  spec/forms/personal_details_form_spec.rb
  spec/forms/poor_performance_form_spec.rb
  spec/forms/provide_mobile_number_form_spec.rb
  spec/forms/reminders/email_verification_form_spec.rb
  spec/forms/reminders/personal_details_form_spec.rb
  spec/forms/supply_teacher_form_spec.rb
  spec/forms/unsubscribe/confirmation_form_spec.rb
  spec/mailers/reminder_mailer_spec.rb
  spec/requests/admin/admin_amendments_spec.rb
  spec/requests/unsubscribe_spec.rb
Labels: deploy

#3520 Allow searching by payment id
  app/models/claim/search.rb
  app/views/admin/claims/search.html.erb
  spec/models/claim/search_spec.rb
Labels: deploy

#3521 CAPT 2143/admin search not finding ey emails
  app/models/claim/search.rb
  spec/models/claim/search_spec.rb
Labels: deploy

#3516 [CAPT-2145] Refactor controller callbacks
  app/controllers/claims_form_callbacks.rb
  app/forms/bank_details_form.rb
  app/forms/information_provided_form.rb
  app/forms/personal_details_form.rb
  app/models/journeys/answers_student_loans_details_updater.rb
  app/models/journeys/base.rb
  app/models/journeys/session_answers.rb
  app/views/claims/address.html.erb
  app/views/claims/current_school.html.erb
  app/views/student_loans/claims/claim_school.html.erb
  spec/features/hmrc_bank_validation_spec.rb
  spec/forms/bank_details_form_spec.rb
  spec/forms/personal_details_form_spec.rb
Labels: deploy

#3507 CAPT 2083/slc upload audit
  app/jobs/file_importer_job.rb
  app/jobs/import_student_loans_data_job.rb
  app/jobs/student_loan_amount_check_job.rb
  app/jobs/student_loan_plan_check_job.rb
  app/models/claim.rb
  app/models/claim_student_loan_details_updater.rb
  app/models/policies/student_loans/eligibility.rb
  app/views/admin/amendments/index.html.erb
  spec/jobs/student_loan_amount_check_job_spec.rb
  spec/jobs/student_loan_plan_check_job_spec.rb
  spec/models/claim_student_loan_details_updater_spec-old.rb
  spec/models/claim_student_loan_details_updater_spec.rb
Labels: deploy

#3530 Don't render link if no email
  app/views/admin/support_tickets/_widget.html.erb
Labels: deploy

#3533 Update govuk 5.7.1 => 5.8.0
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/a11y_dialog.scss
  app/assets/stylesheets/components/accessible_autocomplete_tweaks.scss
  app/assets/stylesheets/components/cookie_banner.scss
  app/assets/stylesheets/components/currency_input.scss
  app/assets/stylesheets/components/flash.scss
  app/assets/stylesheets/components/tag.scss
  package.json
  yarn.lock
Labels: deploy

#3532 [CAPT-1335] Copy tweak: update info provided with SLC
  app/views/claims/information_provided.html.erb
  app/views/further_education_payments/claims/information_provided.html.erb
  spec/features/early_career_payments/early_career_payments_claim_spec.rb
  spec/features/further_education_payments/happy_path_spec.rb
  spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
Labels: deploy
